//! This file was automatically generated 
//! by [Mamba Bronze](https://github.com/Redhawk18/mambaBronze)

use std::{fmt::{Display, Formatter, Result}, string::String};

/// Holds all glyphs of the Phosphor font
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy)]
pub enum Phosphor {
    Acorn,
    AddressBook,
    AddressBookTabs,
    AirTrafficControl,
    Airplane,
    AirplaneInFlight,
    AirplaneLanding,
    AirplaneTakeoff,
    AirplaneTaxiing,
    AirplaneTilt,
    Airplay,
    Alarm,
    Alien,
    AlignBottom,
    AlignBottomSimple,
    AlignCenterHorizontal,
    AlignCenterHorizontalSimple,
    AlignCenterVertical,
    AlignCenterVerticalSimple,
    AlignLeft,
    AlignLeftSimple,
    AlignRight,
    AlignRightSimple,
    AlignTop,
    AlignTopSimple,
    AmazonLogo,
    Ambulance,
    Anchor,
    AnchorSimple,
    AndroidLogo,
    Angle,
    AngularLogo,
    Aperture,
    AppStoreLogo,
    AppWindow,
    AppleLogo,
    ApplePodcastsLogo,
    ApproximateEquals,
    Archive,
    Armchair,
    ArrowArcLeft,
    ArrowArcRight,
    ArrowBendDoubleUpLeft,
    ArrowBendDoubleUpRight,
    ArrowBendDownLeft,
    ArrowBendDownRight,
    ArrowBendLeftDown,
    ArrowBendLeftUp,
    ArrowBendRightDown,
    ArrowBendRightUp,
    ArrowBendUpLeft,
    ArrowBendUpRight,
    ArrowCircleDown,
    ArrowCircleDownLeft,
    ArrowCircleDownRight,
    ArrowCircleLeft,
    ArrowCircleRight,
    ArrowCircleUp,
    ArrowCircleUpLeft,
    ArrowCircleUpRight,
    ArrowClockwise,
    ArrowCounterClockwise,
    ArrowDown,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowElbowDownLeft,
    ArrowElbowDownRight,
    ArrowElbowLeft,
    ArrowElbowLeftDown,
    ArrowElbowLeftUp,
    ArrowElbowRight,
    ArrowElbowRightDown,
    ArrowElbowRightUp,
    ArrowElbowUpLeft,
    ArrowElbowUpRight,
    ArrowFatDown,
    ArrowFatLeft,
    ArrowFatLineDown,
    ArrowFatLineLeft,
    ArrowFatLineRight,
    ArrowFatLineUp,
    ArrowFatLinesDown,
    ArrowFatLinesLeft,
    ArrowFatLinesRight,
    ArrowFatLinesUp,
    ArrowFatRight,
    ArrowFatUp,
    ArrowLeft,
    ArrowLineDown,
    ArrowLineDownLeft,
    ArrowLineDownRight,
    ArrowLineLeft,
    ArrowLineRight,
    ArrowLineUp,
    ArrowLineUpLeft,
    ArrowLineUpRight,
    ArrowRight,
    ArrowSquareDown,
    ArrowSquareDownLeft,
    ArrowSquareDownRight,
    ArrowSquareIn,
    ArrowSquareLeft,
    ArrowSquareOut,
    ArrowSquareRight,
    ArrowSquareUp,
    ArrowSquareUpLeft,
    ArrowSquareUpRight,
    ArrowUDownLeft,
    ArrowUDownRight,
    ArrowULeftDown,
    ArrowULeftUp,
    ArrowURightDown,
    ArrowURightUp,
    ArrowUUpLeft,
    ArrowUUpRight,
    ArrowUp,
    ArrowUpLeft,
    ArrowUpRight,
    ArrowsClockwise,
    ArrowsCounterClockwise,
    ArrowsDownUp,
    ArrowsHorizontal,
    ArrowsIn,
    ArrowsInCardinal,
    ArrowsInLineHorizontal,
    ArrowsInLineVertical,
    ArrowsInSimple,
    ArrowsLeftRight,
    ArrowsMerge,
    ArrowsOut,
    ArrowsOutCardinal,
    ArrowsOutLineHorizontal,
    ArrowsOutLineVertical,
    ArrowsOutSimple,
    ArrowsSplit,
    ArrowsVertical,
    Article,
    ArticleMedium,
    ArticleNyTimes,
    Asclepius,
    Caduceus,
    Asterisk,
    AsteriskSimple,
    At,
    Atom,
    Avocado,
    Axe,
    Baby,
    BabyCarriage,
    Backpack,
    Backspace,
    Bag,
    BagSimple,
    Balloon,
    Bandaids,
    Bank,
    Barbell,
    Barcode,
    Barn,
    Barricade,
    Baseball,
    BaseballCap,
    BaseballHelmet,
    Basket,
    Basketball,
    Bathtub,
    BatteryCharging,
    BatteryChargingVertical,
    BatteryEmpty,
    BatteryFull,
    BatteryHigh,
    BatteryLow,
    BatteryMedium,
    BatteryPlus,
    BatteryPlusVertical,
    BatteryVerticalEmpty,
    BatteryVerticalFull,
    BatteryVerticalHigh,
    BatteryVerticalLow,
    BatteryVerticalMedium,
    BatteryWarning,
    BatteryWarningVertical,
    BeachBall,
    Beanie,
    Bed,
    BeerBottle,
    BeerStein,
    BehanceLogo,
    Bell,
    BellRinging,
    BellSimple,
    BellSimpleRinging,
    BellSimpleSlash,
    BellSimpleZ,
    BellSlash,
    BellZ,
    Belt,
    BezierCurve,
    Bicycle,
    Binary,
    Binoculars,
    Biohazard,
    Bird,
    Blueprint,
    Bluetooth,
    BluetoothConnected,
    BluetoothSlash,
    BluetoothX,
    Boat,
    Bomb,
    Bone,
    Book,
    BookBookmark,
    BookOpen,
    BookOpenText,
    BookOpenUser,
    Bookmark,
    BookmarkSimple,
    Bookmarks,
    BookmarksSimple,
    Books,
    Boot,
    Boules,
    BoundingBox,
    BowlFood,
    BowlSteam,
    BowlingBall,
    BoxArrowDown,
    ArchiveBox,
    BoxArrowUp,
    BoxingGlove,
    BracketsAngle,
    BracketsCurly,
    BracketsRound,
    BracketsSquare,
    Brain,
    Brandy,
    Bread,
    Bridge,
    Briefcase,
    BriefcaseMetal,
    Broadcast,
    Broom,
    Browser,
    Browsers,
    Bug,
    BugBeetle,
    BugDroid,
    Building,
    BuildingApartment,
    BuildingOffice,
    Buildings,
    Bulldozer,
    Bus,
    Butterfly,
    CableCar,
    Cactus,
    Cake,
    Calculator,
    Calendar,
    CalendarBlank,
    CalendarCheck,
    CalendarDot,
    CalendarDots,
    CalendarHeart,
    CalendarMinus,
    CalendarPlus,
    CalendarSlash,
    CalendarStar,
    CalendarX,
    CallBell,
    Camera,
    CameraPlus,
    CameraRotate,
    CameraSlash,
    Campfire,
    Car,
    CarBattery,
    CarProfile,
    CarSimple,
    Cardholder,
    Cards,
    CardsThree,
    CaretCircleDoubleDown,
    CaretCircleDoubleLeft,
    CaretCircleDoubleRight,
    CaretCircleDoubleUp,
    CaretCircleDown,
    CaretCircleLeft,
    CaretCircleRight,
    CaretCircleUp,
    CaretCircleUpDown,
    CaretDoubleDown,
    CaretDoubleLeft,
    CaretDoubleRight,
    CaretDoubleUp,
    CaretDown,
    CaretLeft,
    CaretLineDown,
    CaretLineLeft,
    CaretLineRight,
    CaretLineUp,
    CaretRight,
    CaretUp,
    CaretUpDown,
    Carrot,
    CashRegister,
    CassetteTape,
    CastleTurret,
    Cat,
    CellSignalFull,
    CellSignalHigh,
    CellSignalLow,
    CellSignalMedium,
    CellSignalNone,
    CellSignalSlash,
    CellSignalX,
    CellTower,
    Certificate,
    Chair,
    Chalkboard,
    ChalkboardSimple,
    ChalkboardTeacher,
    Champagne,
    ChargingStation,
    ChartBar,
    ChartBarHorizontal,
    ChartDonut,
    ChartLine,
    ChartLineDown,
    ChartLineUp,
    ChartPie,
    ChartPieSlice,
    ChartPolar,
    ChartScatter,
    Chat,
    ChatCentered,
    ChatCenteredDots,
    ChatCenteredSlash,
    ChatCenteredText,
    ChatCircle,
    ChatCircleDots,
    ChatCircleSlash,
    ChatCircleText,
    ChatDots,
    ChatSlash,
    ChatTeardrop,
    ChatTeardropDots,
    ChatTeardropSlash,
    ChatTeardropText,
    ChatText,
    Chats,
    ChatsCircle,
    ChatsTeardrop,
    Check,
    CheckCircle,
    CheckFat,
    CheckSquare,
    CheckSquareOffset,
    Checkerboard,
    Checks,
    Cheers,
    Cheese,
    ChefHat,
    Cherries,
    Church,
    Cigarette,
    CigaretteSlash,
    Circle,
    CircleDashed,
    CircleHalf,
    CircleHalfTilt,
    CircleNotch,
    CirclesFour,
    CirclesThree,
    CirclesThreePlus,
    Circuitry,
    City,
    Clipboard,
    ClipboardText,
    Clock,
    ClockAfternoon,
    ClockClockwise,
    ClockCountdown,
    ClockCounterClockwise,
    ClockUser,
    ClosedCaptioning,
    Cloud,
    CloudArrowDown,
    CloudArrowUp,
    CloudCheck,
    CloudFog,
    CloudLightning,
    CloudMoon,
    CloudRain,
    CloudSlash,
    CloudSnow,
    CloudSun,
    CloudWarning,
    CloudX,
    Clover,
    Club,
    CoatHanger,
    CodaLogo,
    Code,
    CodeBlock,
    CodeSimple,
    CodepenLogo,
    CodesandboxLogo,
    Coffee,
    CoffeeBean,
    Coin,
    CoinVertical,
    Coins,
    Columns,
    ColumnsPlusLeft,
    ColumnsPlusRight,
    Command,
    Compass,
    CompassRose,
    CompassTool,
    ComputerTower,
    Confetti,
    ContactlessPayment,
    Control,
    Cookie,
    CookingPot,
    Copy,
    CopySimple,
    Copyleft,
    Copyright,
    CornersIn,
    CornersOut,
    Couch,
    CourtBasketball,
    Cow,
    CowboyHat,
    Cpu,
    Crane,
    CraneTower,
    CreditCard,
    Cricket,
    Crop,
    Cross,
    Crosshair,
    CrosshairSimple,
    Crown,
    CrownCross,
    CrownSimple,
    Cube,
    CubeFocus,
    CubeTransparent,
    CurrencyBtc,
    CurrencyCircleDollar,
    CurrencyCny,
    CurrencyDollar,
    CurrencyDollarSimple,
    CurrencyEth,
    CurrencyEur,
    CurrencyGbp,
    CurrencyInr,
    CurrencyJpy,
    CurrencyKrw,
    CurrencyKzt,
    CurrencyNgn,
    CurrencyRub,
    Cursor,
    CursorClick,
    CursorText,
    Cylinder,
    Database,
    Desk,
    Desktop,
    DesktopTower,
    Detective,
    DevToLogo,
    DeviceMobile,
    DeviceMobileCamera,
    DeviceMobileSlash,
    DeviceMobileSpeaker,
    DeviceRotate,
    DeviceTablet,
    DeviceTabletCamera,
    DeviceTabletSpeaker,
    Devices,
    Diamond,
    DiamondsFour,
    DiceFive,
    DiceFour,
    DiceOne,
    DiceSix,
    DiceThree,
    DiceTwo,
    Disc,
    DiscoBall,
    DiscordLogo,
    Divide,
    Dna,
    Dog,
    Door,
    DoorOpen,
    Dot,
    DotOutline,
    DotsNine,
    DotsSix,
    DotsSixVertical,
    DotsThree,
    DotsThreeCircle,
    DotsThreeCircleVertical,
    DotsThreeOutline,
    DotsThreeOutlineVertical,
    DotsThreeVertical,
    Download,
    DownloadSimple,
    Dress,
    Dresser,
    DribbbleLogo,
    Drone,
    Drop,
    DropHalf,
    DropHalfBottom,
    DropSimple,
    DropSlash,
    DropboxLogo,
    Ear,
    EarSlash,
    Egg,
    EggCrack,
    Eject,
    EjectSimple,
    Elevator,
    Empty,
    Engine,
    Envelope,
    EnvelopeOpen,
    EnvelopeSimple,
    EnvelopeSimpleOpen,
    Equalizer,
    Equals,
    Eraser,
    EscalatorDown,
    EscalatorUp,
    Exam,
    ExclamationMark,
    Exclude,
    ExcludeSquare,
    Export,
    Eye,
    EyeClosed,
    EyeSlash,
    Eyedropper,
    EyedropperSample,
    Eyeglasses,
    Eyes,
    FaceMask,
    FacebookLogo,
    Factory,
    Faders,
    FadersHorizontal,
    FalloutShelter,
    Fan,
    Farm,
    FastForward,
    FastForwardCircle,
    Feather,
    FediverseLogo,
    FigmaLogo,
    File,
    FileArchive,
    FileArrowDown,
    FileArrowUp,
    FileAudio,
    FileC,
    FileCSharp,
    FileCloud,
    FileCode,
    FileCpp,
    FileCss,
    FileCsv,
    FileDashed,
    FileDotted,
    FileDoc,
    FileHtml,
    FileImage,
    FileIni,
    FileJpg,
    FileJs,
    FileJsx,
    FileLock,
    FileMagnifyingGlass,
    FileSearch,
    FileMd,
    FileMinus,
    FilePdf,
    FilePlus,
    FilePng,
    FilePpt,
    FilePy,
    FileRs,
    FileSql,
    FileSvg,
    FileText,
    FileTs,
    FileTsx,
    FileTxt,
    FileVideo,
    FileVue,
    FileX,
    FileXls,
    FileZip,
    Files,
    FilmReel,
    FilmScript,
    FilmSlate,
    FilmStrip,
    Fingerprint,
    FingerprintSimple,
    FinnTheHuman,
    Fire,
    FireExtinguisher,
    FireSimple,
    FireTruck,
    FirstAid,
    FirstAidKit,
    Fish,
    FishSimple,
    Flag,
    FlagBanner,
    FlagBannerFold,
    FlagCheckered,
    FlagPennant,
    Flame,
    Flashlight,
    Flask,
    FlipHorizontal,
    FlipVertical,
    FloppyDisk,
    FloppyDiskBack,
    FlowArrow,
    Flower,
    FlowerLotus,
    FlowerTulip,
    FlyingSaucer,
    Folder,
    FolderNotch,
    FolderDashed,
    FolderDotted,
    FolderLock,
    FolderMinus,
    FolderNotchMinus,
    FolderOpen,
    FolderNotchOpen,
    FolderPlus,
    FolderNotchPlus,
    FolderSimple,
    FolderSimpleDashed,
    FolderSimpleDotted,
    FolderSimpleLock,
    FolderSimpleMinus,
    FolderSimplePlus,
    FolderSimpleStar,
    FolderSimpleUser,
    FolderStar,
    FolderUser,
    Folders,
    Football,
    FootballHelmet,
    Footprints,
    ForkKnife,
    FourK,
    FrameCorners,
    FramerLogo,
    Function,
    Funnel,
    FunnelSimple,
    FunnelSimpleX,
    FunnelX,
    GameController,
    Garage,
    GasCan,
    GasPump,
    Gauge,
    Gavel,
    Gear,
    GearFine,
    GearSix,
    GenderFemale,
    GenderIntersex,
    GenderMale,
    GenderNeuter,
    GenderNonbinary,
    GenderTransgender,
    Ghost,
    Gif,
    Gift,
    GitBranch,
    GitCommit,
    GitDiff,
    GitFork,
    GitMerge,
    GitPullRequest,
    GithubLogo,
    GitlabLogo,
    GitlabLogoSimple,
    Globe,
    GlobeHemisphereEast,
    GlobeHemisphereWest,
    GlobeSimple,
    GlobeSimpleX,
    GlobeStand,
    GlobeX,
    Goggles,
    Golf,
    GoodreadsLogo,
    GoogleCardboardLogo,
    GoogleChromeLogo,
    GoogleDriveLogo,
    GoogleLogo,
    GooglePhotosLogo,
    GooglePlayLogo,
    GooglePodcastsLogo,
    Gps,
    GpsFix,
    GpsSlash,
    Gradient,
    GraduationCap,
    Grains,
    GrainsSlash,
    Graph,
    GraphicsCard,
    GreaterThan,
    GreaterThanOrEqual,
    GridFour,
    GridNine,
    Guitar,
    HairDryer,
    Hamburger,
    Hammer,
    Hand,
    HandArrowDown,
    HandArrowUp,
    HandCoins,
    HandDeposit,
    HandEye,
    HandFist,
    HandGrabbing,
    HandHeart,
    HandPalm,
    HandPeace,
    HandPointing,
    HandSoap,
    HandSwipeLeft,
    HandSwipeRight,
    HandTap,
    HandWaving,
    HandWithdraw,
    Handbag,
    HandbagSimple,
    HandsClapping,
    HandsPraying,
    Handshake,
    HardDrive,
    HardDrives,
    HardHat,
    Hash,
    HashStraight,
    HeadCircuit,
    Headlights,
    Headphones,
    Headset,
    Heart,
    HeartBreak,
    HeartHalf,
    HeartStraight,
    HeartStraightBreak,
    Heartbeat,
    Hexagon,
    HighDefinition,
    HighHeel,
    Highlighter,
    HighlighterCircle,
    Hockey,
    Hoodie,
    Horse,
    Hospital,
    Hourglass,
    HourglassHigh,
    HourglassLow,
    HourglassMedium,
    HourglassSimple,
    HourglassSimpleHigh,
    HourglassSimpleLow,
    HourglassSimpleMedium,
    House,
    HouseLine,
    HouseSimple,
    Hurricane,
    IceCream,
    IdentificationBadge,
    IdentificationCard,
    Image,
    ImageBroken,
    ImageSquare,
    Images,
    ImagesSquare,
    Infinity,
    Lemniscate,
    Info,
    InstagramLogo,
    Intersect,
    IntersectSquare,
    IntersectThree,
    Intersection,
    Invoice,
    Island,
    Jar,
    JarLabel,
    Jeep,
    Joystick,
    Kanban,
    Key,
    KeyReturn,
    Keyboard,
    Keyhole,
    Knife,
    Ladder,
    LadderSimple,
    Lamp,
    LampPendant,
    Laptop,
    Lasso,
    LastfmLogo,
    Layout,
    Leaf,
    Lectern,
    Lego,
    LegoSmiley,
    LessThan,
    LessThanOrEqual,
    LetterCircleH,
    LetterCircleP,
    LetterCircleV,
    Lifebuoy,
    Lightbulb,
    LightbulbFilament,
    Lighthouse,
    Lightning,
    LightningA,
    LightningSlash,
    LineSegment,
    LineSegments,
    LineVertical,
    Link,
    LinkBreak,
    LinkSimple,
    LinkSimpleBreak,
    LinkSimpleHorizontal,
    LinkSimpleHorizontalBreak,
    LinkedinLogo,
    LinktreeLogo,
    LinuxLogo,
    List,
    ListBullets,
    ListChecks,
    ListDashes,
    ListHeart,
    ListMagnifyingGlass,
    ListNumbers,
    ListPlus,
    ListStar,
    Lock,
    LockKey,
    LockKeyOpen,
    LockLaminated,
    LockLaminatedOpen,
    LockOpen,
    LockSimple,
    LockSimpleOpen,
    Lockers,
    Log,
    MagicWand,
    Magnet,
    MagnetStraight,
    MagnifyingGlass,
    MagnifyingGlassMinus,
    MagnifyingGlassPlus,
    Mailbox,
    MapPin,
    MapPinArea,
    MapPinLine,
    MapPinPlus,
    MapPinSimple,
    MapPinSimpleArea,
    MapPinSimpleLine,
    MapTrifold,
    MarkdownLogo,
    MarkerCircle,
    Martini,
    MaskHappy,
    MaskSad,
    MastodonLogo,
    MathOperations,
    MatrixLogo,
    Medal,
    MedalMilitary,
    MediumLogo,
    Megaphone,
    MegaphoneSimple,
    MemberOf,
    Memory,
    MessengerLogo,
    MetaLogo,
    Meteor,
    Metronome,
    Microphone,
    MicrophoneSlash,
    MicrophoneStage,
    Microscope,
    MicrosoftExcelLogo,
    MicrosoftOutlookLogo,
    MicrosoftPowerpointLogo,
    MicrosoftTeamsLogo,
    MicrosoftWordLogo,
    Minus,
    MinusCircle,
    MinusSquare,
    Money,
    MoneyWavy,
    Monitor,
    MonitorArrowUp,
    MonitorPlay,
    Moon,
    MoonStars,
    Moped,
    MopedFront,
    Mosque,
    Motorcycle,
    Mountains,
    Mouse,
    MouseLeftClick,
    MouseMiddleClick,
    MouseRightClick,
    MouseScroll,
    MouseSimple,
    MusicNote,
    MusicNoteSimple,
    MusicNotes,
    MusicNotesMinus,
    MusicNotesPlus,
    MusicNotesSimple,
    NavigationArrow,
    Needle,
    Network,
    NetworkSlash,
    NetworkX,
    Newspaper,
    NewspaperClipping,
    NotEquals,
    NotMemberOf,
    NotSubsetOf,
    NotSupersetOf,
    Notches,
    Note,
    NoteBlank,
    NotePencil,
    Notebook,
    Notepad,
    Notification,
    NotionLogo,
    NuclearPlant,
    NumberCircleEight,
    NumberCircleFive,
    NumberCircleFour,
    NumberCircleNine,
    NumberCircleOne,
    NumberCircleSeven,
    NumberCircleSix,
    NumberCircleThree,
    NumberCircleTwo,
    NumberCircleZero,
    NumberEight,
    NumberFive,
    NumberFour,
    NumberNine,
    NumberOne,
    NumberSeven,
    NumberSix,
    NumberSquareEight,
    NumberSquareFive,
    NumberSquareFour,
    NumberSquareNine,
    NumberSquareOne,
    NumberSquareSeven,
    NumberSquareSix,
    NumberSquareThree,
    NumberSquareTwo,
    NumberSquareZero,
    NumberThree,
    NumberTwo,
    NumberZero,
    Numpad,
    Nut,
    NyTimesLogo,
    Octagon,
    OfficeChair,
    Onigiri,
    OpenAiLogo,
    Option,
    Orange,
    OrangeSlice,
    Oven,
    Package,
    PaintBrush,
    PaintBrushBroad,
    PaintBrushHousehold,
    PaintBucket,
    PaintRoller,
    Palette,
    Panorama,
    Pants,
    PaperPlane,
    PaperPlaneRight,
    PaperPlaneTilt,
    Paperclip,
    PaperclipHorizontal,
    Parachute,
    Paragraph,
    Parallelogram,
    Park,
    Password,
    Path,
    PatreonLogo,
    Pause,
    PauseCircle,
    PawPrint,
    PaypalLogo,
    Peace,
    Pen,
    PenNib,
    PenNibStraight,
    Pencil,
    PencilCircle,
    PencilLine,
    PencilRuler,
    PencilSimple,
    PencilSimpleLine,
    PencilSimpleSlash,
    PencilSlash,
    Pentagon,
    Pentagram,
    Pepper,
    Percent,
    Person,
    PersonArmsSpread,
    PersonSimple,
    PersonSimpleBike,
    PersonSimpleCircle,
    PersonSimpleHike,
    PersonSimpleRun,
    PersonSimpleSki,
    PersonSimpleSnowboard,
    PersonSimpleSwim,
    PersonSimpleTaiChi,
    PersonSimpleThrow,
    PersonSimpleWalk,
    Perspective,
    Phone,
    PhoneCall,
    PhoneDisconnect,
    PhoneIncoming,
    PhoneList,
    PhoneOutgoing,
    PhonePause,
    PhonePlus,
    PhoneSlash,
    PhoneTransfer,
    PhoneX,
    Logo,
    Pi,
    PianoKeys,
    PicnicTable,
    PictureInPicture,
    PiggyBank,
    Pill,
    PingPong,
    PintGlass,
    PinterestLogo,
    Pinwheel,
    Pipe,
    PipeWrench,
    PixLogo,
    Pizza,
    Placeholder,
    Planet,
    Plant,
    Play,
    PlayCircle,
    PlayPause,
    Playlist,
    Plug,
    PlugCharging,
    Plugs,
    PlugsConnected,
    Plus,
    PlusCircle,
    PlusMinus,
    PlusSquare,
    PokerChip,
    PoliceCar,
    Polygon,
    Popcorn,
    Popsicle,
    PottedPlant,
    Power,
    Prescription,
    Presentation,
    PresentationChart,
    Printer,
    Prohibit,
    ProhibitInset,
    ProjectorScreen,
    ProjectorScreenChart,
    Pulse,
    Activity,
    PushPin,
    PushPinSimple,
    PushPinSimpleSlash,
    PushPinSlash,
    PuzzlePiece,
    QrCode,
    Question,
    QuestionMark,
    Queue,
    Quotes,
    Rabbit,
    Racquet,
    Radical,
    Radio,
    RadioButton,
    Radioactive,
    Rainbow,
    RainbowCloud,
    Ranking,
    ReadCvLogo,
    Receipt,
    ReceiptX,
    Record,
    Rectangle,
    RectangleDashed,
    Recycle,
    RedditLogo,
    Repeat,
    RepeatOnce,
    ReplitLogo,
    Resize,
    Rewind,
    RewindCircle,
    RoadHorizon,
    Robot,
    Rocket,
    RocketLaunch,
    Rows,
    RowsPlusBottom,
    RowsPlusTop,
    Rss,
    RssSimple,
    Rug,
    Ruler,
    Sailboat,
    Scales,
    Scan,
    ScanSmiley,
    Scissors,
    Scooter,
    Screencast,
    Screwdriver,
    Scribble,
    ScribbleLoop,
    Scroll,
    Seal,
    CircleWavy,
    SealCheck,
    CircleWavyCheck,
    SealPercent,
    SealQuestion,
    CircleWavyQuestion,
    SealWarning,
    CircleWavyWarning,
    Seat,
    Seatbelt,
    SecurityCamera,
    Selection,
    SelectionAll,
    SelectionBackground,
    SelectionForeground,
    SelectionInverse,
    SelectionPlus,
    SelectionSlash,
    Shapes,
    Share,
    ShareFat,
    ShareNetwork,
    Shield,
    ShieldCheck,
    ShieldCheckered,
    ShieldChevron,
    ShieldPlus,
    ShieldSlash,
    ShieldStar,
    ShieldWarning,
    ShippingContainer,
    ShirtFolded,
    ShootingStar,
    ShoppingBag,
    ShoppingBagOpen,
    ShoppingCart,
    ShoppingCartSimple,
    Shovel,
    Shower,
    Shrimp,
    Shuffle,
    ShuffleAngular,
    ShuffleSimple,
    Sidebar,
    SidebarSimple,
    Sigma,
    SignIn,
    SignOut,
    Signature,
    Signpost,
    SimCard,
    Siren,
    SketchLogo,
    SkipBack,
    SkipBackCircle,
    SkipForward,
    SkipForwardCircle,
    Skull,
    SkypeLogo,
    SlackLogo,
    Sliders,
    SlidersHorizontal,
    Slideshow,
    Smiley,
    SmileyAngry,
    SmileyBlank,
    SmileyMeh,
    SmileyMelting,
    SmileyNervous,
    SmileySad,
    SmileySticker,
    SmileyWink,
    SmileyXEyes,
    SnapchatLogo,
    Sneaker,
    SneakerMove,
    Snowflake,
    SoccerBall,
    Sock,
    SolarPanel,
    SolarRoof,
    SortAscending,
    SortDescending,
    SoundcloudLogo,
    Spade,
    Sparkle,
    SpeakerHifi,
    SpeakerHigh,
    SpeakerLow,
    SpeakerNone,
    SpeakerSimpleHigh,
    SpeakerSimpleLow,
    SpeakerSimpleNone,
    SpeakerSimpleSlash,
    SpeakerSimpleX,
    SpeakerSlash,
    SpeakerX,
    Speedometer,
    Sphere,
    Spinner,
    SpinnerBall,
    SpinnerGap,
    Spiral,
    SplitHorizontal,
    SplitVertical,
    SpotifyLogo,
    SprayBottle,
    Square,
    SquareHalf,
    SquareHalfBottom,
    SquareLogo,
    SquareSplitHorizontal,
    SquareSplitVertical,
    SquaresFour,
    Stack,
    StackMinus,
    StackOverflowLogo,
    StackPlus,
    StackSimple,
    Stairs,
    Stamp,
    StandardDefinition,
    Star,
    StarAndCrescent,
    StarFour,
    StarHalf,
    StarOfDavid,
    SteamLogo,
    SteeringWheel,
    Steps,
    Stethoscope,
    Sticker,
    Stool,
    Stop,
    StopCircle,
    Storefront,
    Strategy,
    StripeLogo,
    Student,
    SubsetOf,
    SubsetProperOf,
    Subtitles,
    SubtitlesSlash,
    Subtract,
    SubtractSquare,
    Subway,
    Suitcase,
    SuitcaseRolling,
    SuitcaseSimple,
    Sun,
    SunDim,
    SunHorizon,
    Sunglasses,
    SupersetOf,
    SupersetProperOf,
    Swap,
    Swatches,
    SwimmingPool,
    Sword,
    Synagogue,
    Syringe,
    TShirt,
    Table,
    Tabs,
    Tag,
    TagChevron,
    TagSimple,
    Target,
    Taxi,
    TeaBag,
    TelegramLogo,
    Television,
    TelevisionSimple,
    TennisBall,
    Tent,
    Terminal,
    TerminalWindow,
    TestTube,
    TextAUnderline,
    TextAa,
    TextAlignCenter,
    TextAlignJustify,
    TextAlignLeft,
    TextAlignRight,
    TextB,
    TextBolder,
    TextColumns,
    TextH,
    TextHFive,
    TextHFour,
    TextHOne,
    TextHSix,
    TextHThree,
    TextHTwo,
    TextIndent,
    TextItalic,
    TextOutdent,
    TextStrikethrough,
    TextSubscript,
    TextSuperscript,
    TextT,
    TextTSlash,
    TextUnderline,
    Textbox,
    Thermometer,
    ThermometerCold,
    ThermometerHot,
    ThermometerSimple,
    ThreadsLogo,
    ThreeD,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    TidalLogo,
    TiktokLogo,
    Tilde,
    Timer,
    TipJar,
    Tipi,
    Tire,
    ToggleLeft,
    ToggleRight,
    Toilet,
    ToiletPaper,
    Toolbox,
    Tooth,
    Tornado,
    Tote,
    ToteSimple,
    Towel,
    Tractor,
    Trademark,
    TrademarkRegistered,
    TrafficCone,
    TrafficSign,
    TrafficSignal,
    Train,
    TrainRegional,
    TrainSimple,
    Tram,
    Translate,
    Trash,
    TrashSimple,
    Tray,
    TrayArrowDown,
    ArchiveTray,
    TrayArrowUp,
    TreasureChest,
    Tree,
    TreeEvergreen,
    TreePalm,
    TreeStructure,
    TreeView,
    TrendDown,
    TrendUp,
    Triangle,
    TriangleDashed,
    Trolley,
    TrolleySuitcase,
    Trophy,
    Truck,
    TruckTrailer,
    TumblrLogo,
    TwitchLogo,
    TwitterLogo,
    Umbrella,
    UmbrellaSimple,
    Union,
    Unite,
    UniteSquare,
    Upload,
    UploadSimple,
    Usb,
    User,
    UserCheck,
    UserCircle,
    UserCircleCheck,
    UserCircleDashed,
    UserCircleGear,
    UserCircleMinus,
    UserCirclePlus,
    UserFocus,
    UserGear,
    UserList,
    UserMinus,
    UserPlus,
    UserRectangle,
    UserSound,
    UserSquare,
    UserSwitch,
    Users,
    UsersFour,
    UsersThree,
    Van,
    Vault,
    VectorThree,
    VectorTwo,
    Vibrate,
    Video,
    VideoCamera,
    VideoCameraSlash,
    VideoConference,
    Vignette,
    VinylRecord,
    VirtualReality,
    Virus,
    Visor,
    Voicemail,
    Volleyball,
    Wall,
    Wallet,
    Warehouse,
    Warning,
    WarningCircle,
    WarningDiamond,
    WarningOctagon,
    WashingMachine,
    Watch,
    WaveSawtooth,
    WaveSine,
    WaveSquare,
    WaveTriangle,
    Waveform,
    WaveformSlash,
    Waves,
    Webcam,
    WebcamSlash,
    WebhooksLogo,
    WechatLogo,
    WhatsappLogo,
    Wheelchair,
    WheelchairMotion,
    WifiHigh,
    WifiLow,
    WifiMedium,
    WifiNone,
    WifiSlash,
    WifiX,
    Wind,
    Windmill,
    WindowsLogo,
    Wine,
    Wrench,
    X,
    XCircle,
    XLogo,
    XSquare,
    Yarn,
    YinYang,
    YoutubeLogo,
}

/// Converts an [`Phosphor`] into a [`char`]
#[must_use]
pub const fn icon_to_char(icon: Phosphor) -> char {
    match icon {
        Phosphor::Acorn => '\u{eb9a}',
        Phosphor::AddressBook => '\u{e6f8}',
        Phosphor::AddressBookTabs => '\u{ee4e}',
        Phosphor::AirTrafficControl => '\u{ecd8}',
        Phosphor::Airplane => '\u{e002}',
        Phosphor::AirplaneInFlight => '\u{e4fe}',
        Phosphor::AirplaneLanding => '\u{e502}',
        Phosphor::AirplaneTakeoff => '\u{e504}',
        Phosphor::AirplaneTaxiing => '\u{e500}',
        Phosphor::AirplaneTilt => '\u{e5d6}',
        Phosphor::Airplay => '\u{e004}',
        Phosphor::Alarm => '\u{e006}',
        Phosphor::Alien => '\u{e8a6}',
        Phosphor::AlignBottom => '\u{e506}',
        Phosphor::AlignBottomSimple => '\u{eb0c}',
        Phosphor::AlignCenterHorizontal => '\u{e50a}',
        Phosphor::AlignCenterHorizontalSimple => '\u{eb0e}',
        Phosphor::AlignCenterVertical => '\u{e50c}',
        Phosphor::AlignCenterVerticalSimple => '\u{eb10}',
        Phosphor::AlignLeft => '\u{e50e}',
        Phosphor::AlignLeftSimple => '\u{eaee}',
        Phosphor::AlignRight => '\u{e510}',
        Phosphor::AlignRightSimple => '\u{eb12}',
        Phosphor::AlignTop => '\u{e512}',
        Phosphor::AlignTopSimple => '\u{eb14}',
        Phosphor::AmazonLogo => '\u{e96c}',
        Phosphor::Ambulance => '\u{e572}',
        Phosphor::Anchor => '\u{e514}',
        Phosphor::AnchorSimple => '\u{e5d8}',
        Phosphor::AndroidLogo => '\u{e008}',
        Phosphor::Angle => '\u{e7bc}',
        Phosphor::AngularLogo => '\u{eb80}',
        Phosphor::Aperture => '\u{e00a}',
        Phosphor::AppStoreLogo => '\u{e974}',
        Phosphor::AppWindow => '\u{e5da}',
        Phosphor::AppleLogo => '\u{e516}',
        Phosphor::ApplePodcastsLogo => '\u{eb96}',
        Phosphor::ApproximateEquals => '\u{edaa}',
        Phosphor::Archive => '\u{e00c}',
        Phosphor::Armchair => '\u{e012}',
        Phosphor::ArrowArcLeft => '\u{e014}',
        Phosphor::ArrowArcRight => '\u{e016}',
        Phosphor::ArrowBendDoubleUpLeft => '\u{e03a}',
        Phosphor::ArrowBendDoubleUpRight => '\u{e03c}',
        Phosphor::ArrowBendDownLeft => '\u{e018}',
        Phosphor::ArrowBendDownRight => '\u{e01a}',
        Phosphor::ArrowBendLeftDown => '\u{e01c}',
        Phosphor::ArrowBendLeftUp => '\u{e01e}',
        Phosphor::ArrowBendRightDown => '\u{e020}',
        Phosphor::ArrowBendRightUp => '\u{e022}',
        Phosphor::ArrowBendUpLeft => '\u{e024}',
        Phosphor::ArrowBendUpRight => '\u{e026}',
        Phosphor::ArrowCircleDown => '\u{e028}',
        Phosphor::ArrowCircleDownLeft => '\u{e02a}',
        Phosphor::ArrowCircleDownRight => '\u{e02c}',
        Phosphor::ArrowCircleLeft => '\u{e05a}',
        Phosphor::ArrowCircleRight => '\u{e02e}',
        Phosphor::ArrowCircleUp => '\u{e030}',
        Phosphor::ArrowCircleUpLeft => '\u{e032}',
        Phosphor::ArrowCircleUpRight => '\u{e034}',
        Phosphor::ArrowClockwise => '\u{e036}',
        Phosphor::ArrowCounterClockwise => '\u{e038}',
        Phosphor::ArrowDown => '\u{e03e}',
        Phosphor::ArrowDownLeft => '\u{e040}',
        Phosphor::ArrowDownRight => '\u{e042}',
        Phosphor::ArrowElbowDownLeft => '\u{e044}',
        Phosphor::ArrowElbowDownRight => '\u{e046}',
        Phosphor::ArrowElbowLeft => '\u{e048}',
        Phosphor::ArrowElbowLeftDown => '\u{e04a}',
        Phosphor::ArrowElbowLeftUp => '\u{e04c}',
        Phosphor::ArrowElbowRight => '\u{e04e}',
        Phosphor::ArrowElbowRightDown => '\u{e050}',
        Phosphor::ArrowElbowRightUp => '\u{e052}',
        Phosphor::ArrowElbowUpLeft => '\u{e054}',
        Phosphor::ArrowElbowUpRight => '\u{e056}',
        Phosphor::ArrowFatDown => '\u{e518}',
        Phosphor::ArrowFatLeft => '\u{e51a}',
        Phosphor::ArrowFatLineDown => '\u{e51c}',
        Phosphor::ArrowFatLineLeft => '\u{e51e}',
        Phosphor::ArrowFatLineRight => '\u{e520}',
        Phosphor::ArrowFatLineUp => '\u{e522}',
        Phosphor::ArrowFatLinesDown => '\u{e524}',
        Phosphor::ArrowFatLinesLeft => '\u{e526}',
        Phosphor::ArrowFatLinesRight => '\u{e528}',
        Phosphor::ArrowFatLinesUp => '\u{e52a}',
        Phosphor::ArrowFatRight => '\u{e52c}',
        Phosphor::ArrowFatUp => '\u{e52e}',
        Phosphor::ArrowLeft => '\u{e058}',
        Phosphor::ArrowLineDown => '\u{e05c}',
        Phosphor::ArrowLineDownLeft => '\u{e05e}',
        Phosphor::ArrowLineDownRight => '\u{e060}',
        Phosphor::ArrowLineLeft => '\u{e062}',
        Phosphor::ArrowLineRight => '\u{e064}',
        Phosphor::ArrowLineUp => '\u{e066}',
        Phosphor::ArrowLineUpLeft => '\u{e068}',
        Phosphor::ArrowLineUpRight => '\u{e06a}',
        Phosphor::ArrowRight => '\u{e06c}',
        Phosphor::ArrowSquareDown => '\u{e06e}',
        Phosphor::ArrowSquareDownLeft => '\u{e070}',
        Phosphor::ArrowSquareDownRight => '\u{e072}',
        Phosphor::ArrowSquareIn => '\u{e5dc}',
        Phosphor::ArrowSquareLeft => '\u{e074}',
        Phosphor::ArrowSquareOut => '\u{e5de}',
        Phosphor::ArrowSquareRight => '\u{e076}',
        Phosphor::ArrowSquareUp => '\u{e078}',
        Phosphor::ArrowSquareUpLeft => '\u{e07a}',
        Phosphor::ArrowSquareUpRight => '\u{e07c}',
        Phosphor::ArrowUDownLeft => '\u{e07e}',
        Phosphor::ArrowUDownRight => '\u{e080}',
        Phosphor::ArrowULeftDown => '\u{e082}',
        Phosphor::ArrowULeftUp => '\u{e084}',
        Phosphor::ArrowURightDown => '\u{e086}',
        Phosphor::ArrowURightUp => '\u{e088}',
        Phosphor::ArrowUUpLeft => '\u{e08a}',
        Phosphor::ArrowUUpRight => '\u{e08c}',
        Phosphor::ArrowUp => '\u{e08e}',
        Phosphor::ArrowUpLeft => '\u{e090}',
        Phosphor::ArrowUpRight => '\u{e092}',
        Phosphor::ArrowsClockwise => '\u{e094}',
        Phosphor::ArrowsCounterClockwise => '\u{e096}',
        Phosphor::ArrowsDownUp => '\u{e098}',
        Phosphor::ArrowsHorizontal => '\u{eb06}',
        Phosphor::ArrowsIn => '\u{e09a}',
        Phosphor::ArrowsInCardinal => '\u{e09c}',
        Phosphor::ArrowsInLineHorizontal => '\u{e530}',
        Phosphor::ArrowsInLineVertical => '\u{e532}',
        Phosphor::ArrowsInSimple => '\u{e09e}',
        Phosphor::ArrowsLeftRight => '\u{e0a0}',
        Phosphor::ArrowsMerge => '\u{ed3e}',
        Phosphor::ArrowsOut => '\u{e0a2}',
        Phosphor::ArrowsOutCardinal => '\u{e0a4}',
        Phosphor::ArrowsOutLineHorizontal => '\u{e534}',
        Phosphor::ArrowsOutLineVertical => '\u{e536}',
        Phosphor::ArrowsOutSimple => '\u{e0a6}',
        Phosphor::ArrowsSplit => '\u{ed3c}',
        Phosphor::ArrowsVertical => '\u{eb04}',
        Phosphor::Article => '\u{e0a8}',
        Phosphor::ArticleMedium => '\u{e5e0}',
        Phosphor::ArticleNyTimes => '\u{e5e2}',
        Phosphor::Asclepius => '\u{ee34}',
        Phosphor::Caduceus => '\u{ee34}',
        Phosphor::Asterisk => '\u{e0aa}',
        Phosphor::AsteriskSimple => '\u{e832}',
        Phosphor::At => '\u{e0ac}',
        Phosphor::Atom => '\u{e5e4}',
        Phosphor::Avocado => '\u{ee04}',
        Phosphor::Axe => '\u{e9fc}',
        Phosphor::Baby => '\u{e774}',
        Phosphor::BabyCarriage => '\u{e818}',
        Phosphor::Backpack => '\u{e922}',
        Phosphor::Backspace => '\u{e0ae}',
        Phosphor::Bag => '\u{e0b0}',
        Phosphor::BagSimple => '\u{e5e6}',
        Phosphor::Balloon => '\u{e76c}',
        Phosphor::Bandaids => '\u{e0b2}',
        Phosphor::Bank => '\u{e0b4}',
        Phosphor::Barbell => '\u{e0b6}',
        Phosphor::Barcode => '\u{e0b8}',
        Phosphor::Barn => '\u{ec72}',
        Phosphor::Barricade => '\u{e948}',
        Phosphor::Baseball => '\u{e71a}',
        Phosphor::BaseballCap => '\u{ea28}',
        Phosphor::BaseballHelmet => '\u{ee4a}',
        Phosphor::Basket => '\u{e964}',
        Phosphor::Basketball => '\u{e724}',
        Phosphor::Bathtub => '\u{e81e}',
        Phosphor::BatteryCharging => '\u{e0ba}',
        Phosphor::BatteryChargingVertical => '\u{e0bc}',
        Phosphor::BatteryEmpty => '\u{e0be}',
        Phosphor::BatteryFull => '\u{e0c0}',
        Phosphor::BatteryHigh => '\u{e0c2}',
        Phosphor::BatteryLow => '\u{e0c4}',
        Phosphor::BatteryMedium => '\u{e0c6}',
        Phosphor::BatteryPlus => '\u{e808}',
        Phosphor::BatteryPlusVertical => '\u{ec50}',
        Phosphor::BatteryVerticalEmpty => '\u{e7c6}',
        Phosphor::BatteryVerticalFull => '\u{e7c4}',
        Phosphor::BatteryVerticalHigh => '\u{e7c2}',
        Phosphor::BatteryVerticalLow => '\u{e7be}',
        Phosphor::BatteryVerticalMedium => '\u{e7c0}',
        Phosphor::BatteryWarning => '\u{e0c8}',
        Phosphor::BatteryWarningVertical => '\u{e0ca}',
        Phosphor::BeachBall => '\u{ed24}',
        Phosphor::Beanie => '\u{ea2a}',
        Phosphor::Bed => '\u{e0cc}',
        Phosphor::BeerBottle => '\u{e7b0}',
        Phosphor::BeerStein => '\u{eb62}',
        Phosphor::BehanceLogo => '\u{e7f4}',
        Phosphor::Bell => '\u{e0ce}',
        Phosphor::BellRinging => '\u{e5e8}',
        Phosphor::BellSimple => '\u{e0d0}',
        Phosphor::BellSimpleRinging => '\u{e5ea}',
        Phosphor::BellSimpleSlash => '\u{e0d2}',
        Phosphor::BellSimpleZ => '\u{e5ec}',
        Phosphor::BellSlash => '\u{e0d4}',
        Phosphor::BellZ => '\u{e5ee}',
        Phosphor::Belt => '\u{ea2c}',
        Phosphor::BezierCurve => '\u{eb00}',
        Phosphor::Bicycle => '\u{e0d6}',
        Phosphor::Binary => '\u{ee60}',
        Phosphor::Binoculars => '\u{ea64}',
        Phosphor::Biohazard => '\u{e9e0}',
        Phosphor::Bird => '\u{e72c}',
        Phosphor::Blueprint => '\u{eda0}',
        Phosphor::Bluetooth => '\u{e0da}',
        Phosphor::BluetoothConnected => '\u{e0dc}',
        Phosphor::BluetoothSlash => '\u{e0de}',
        Phosphor::BluetoothX => '\u{e0e0}',
        Phosphor::Boat => '\u{e786}',
        Phosphor::Bomb => '\u{ee0a}',
        Phosphor::Bone => '\u{e7f2}',
        Phosphor::Book => '\u{e0e2}',
        Phosphor::BookBookmark => '\u{e0e4}',
        Phosphor::BookOpen => '\u{e0e6}',
        Phosphor::BookOpenText => '\u{e8f2}',
        Phosphor::BookOpenUser => '\u{ede0}',
        Phosphor::Bookmark => '\u{e0e8}',
        Phosphor::BookmarkSimple => '\u{e0ea}',
        Phosphor::Bookmarks => '\u{e0ec}',
        Phosphor::BookmarksSimple => '\u{e5f0}',
        Phosphor::Books => '\u{e758}',
        Phosphor::Boot => '\u{ecca}',
        Phosphor::Boules => '\u{e722}',
        Phosphor::BoundingBox => '\u{e6ce}',
        Phosphor::BowlFood => '\u{eaa4}',
        Phosphor::BowlSteam => '\u{e8e4}',
        Phosphor::BowlingBall => '\u{ea34}',
        Phosphor::BoxArrowDown => '\u{e00e}',
        Phosphor::ArchiveBox => '\u{e00e}',
        Phosphor::BoxArrowUp => '\u{ee54}',
        Phosphor::BoxingGlove => '\u{ea36}',
        Phosphor::BracketsAngle => '\u{e862}',
        Phosphor::BracketsCurly => '\u{e860}',
        Phosphor::BracketsRound => '\u{e864}',
        Phosphor::BracketsSquare => '\u{e85e}',
        Phosphor::Brain => '\u{e74e}',
        Phosphor::Brandy => '\u{e6b4}',
        Phosphor::Bread => '\u{e81c}',
        Phosphor::Bridge => '\u{ea68}',
        Phosphor::Briefcase => '\u{e0ee}',
        Phosphor::BriefcaseMetal => '\u{e5f2}',
        Phosphor::Broadcast => '\u{e0f2}',
        Phosphor::Broom => '\u{ec54}',
        Phosphor::Browser => '\u{e0f4}',
        Phosphor::Browsers => '\u{e0f6}',
        Phosphor::Bug => '\u{e5f4}',
        Phosphor::BugBeetle => '\u{e5f6}',
        Phosphor::BugDroid => '\u{e5f8}',
        Phosphor::Building => '\u{e100}',
        Phosphor::BuildingApartment => '\u{e0fe}',
        Phosphor::BuildingOffice => '\u{e0ff}',
        Phosphor::Buildings => '\u{e102}',
        Phosphor::Bulldozer => '\u{ec6c}',
        Phosphor::Bus => '\u{e106}',
        Phosphor::Butterfly => '\u{ea6e}',
        Phosphor::CableCar => '\u{e49c}',
        Phosphor::Cactus => '\u{e918}',
        Phosphor::Cake => '\u{e780}',
        Phosphor::Calculator => '\u{e538}',
        Phosphor::Calendar => '\u{e108}',
        Phosphor::CalendarBlank => '\u{e10a}',
        Phosphor::CalendarCheck => '\u{e712}',
        Phosphor::CalendarDot => '\u{e7b2}',
        Phosphor::CalendarDots => '\u{e7b4}',
        Phosphor::CalendarHeart => '\u{e8b0}',
        Phosphor::CalendarMinus => '\u{ea14}',
        Phosphor::CalendarPlus => '\u{e714}',
        Phosphor::CalendarSlash => '\u{ea12}',
        Phosphor::CalendarStar => '\u{e8b2}',
        Phosphor::CalendarX => '\u{e10c}',
        Phosphor::CallBell => '\u{e7de}',
        Phosphor::Camera => '\u{e10e}',
        Phosphor::CameraPlus => '\u{ec58}',
        Phosphor::CameraRotate => '\u{e7a4}',
        Phosphor::CameraSlash => '\u{e110}',
        Phosphor::Campfire => '\u{e9d8}',
        Phosphor::Car => '\u{e112}',
        Phosphor::CarBattery => '\u{ee30}',
        Phosphor::CarProfile => '\u{e8cc}',
        Phosphor::CarSimple => '\u{e114}',
        Phosphor::Cardholder => '\u{e5fa}',
        Phosphor::Cards => '\u{e0f8}',
        Phosphor::CardsThree => '\u{ee50}',
        Phosphor::CaretCircleDoubleDown => '\u{e116}',
        Phosphor::CaretCircleDoubleLeft => '\u{e118}',
        Phosphor::CaretCircleDoubleRight => '\u{e11a}',
        Phosphor::CaretCircleDoubleUp => '\u{e11c}',
        Phosphor::CaretCircleDown => '\u{e11e}',
        Phosphor::CaretCircleLeft => '\u{e120}',
        Phosphor::CaretCircleRight => '\u{e122}',
        Phosphor::CaretCircleUp => '\u{e124}',
        Phosphor::CaretCircleUpDown => '\u{e13e}',
        Phosphor::CaretDoubleDown => '\u{e126}',
        Phosphor::CaretDoubleLeft => '\u{e128}',
        Phosphor::CaretDoubleRight => '\u{e12a}',
        Phosphor::CaretDoubleUp => '\u{e12c}',
        Phosphor::CaretDown => '\u{e136}',
        Phosphor::CaretLeft => '\u{e138}',
        Phosphor::CaretLineDown => '\u{e134}',
        Phosphor::CaretLineLeft => '\u{e132}',
        Phosphor::CaretLineRight => '\u{e130}',
        Phosphor::CaretLineUp => '\u{e12e}',
        Phosphor::CaretRight => '\u{e13a}',
        Phosphor::CaretUp => '\u{e13c}',
        Phosphor::CaretUpDown => '\u{e140}',
        Phosphor::Carrot => '\u{ed38}',
        Phosphor::CashRegister => '\u{ed80}',
        Phosphor::CassetteTape => '\u{ed2e}',
        Phosphor::CastleTurret => '\u{e9d0}',
        Phosphor::Cat => '\u{e748}',
        Phosphor::CellSignalFull => '\u{e142}',
        Phosphor::CellSignalHigh => '\u{e144}',
        Phosphor::CellSignalLow => '\u{e146}',
        Phosphor::CellSignalMedium => '\u{e148}',
        Phosphor::CellSignalNone => '\u{e14a}',
        Phosphor::CellSignalSlash => '\u{e14c}',
        Phosphor::CellSignalX => '\u{e14e}',
        Phosphor::CellTower => '\u{ebaa}',
        Phosphor::Certificate => '\u{e766}',
        Phosphor::Chair => '\u{e950}',
        Phosphor::Chalkboard => '\u{e5fc}',
        Phosphor::ChalkboardSimple => '\u{e5fe}',
        Phosphor::ChalkboardTeacher => '\u{e600}',
        Phosphor::Champagne => '\u{eaca}',
        Phosphor::ChargingStation => '\u{e8d0}',
        Phosphor::ChartBar => '\u{e150}',
        Phosphor::ChartBarHorizontal => '\u{e152}',
        Phosphor::ChartDonut => '\u{eaa6}',
        Phosphor::ChartLine => '\u{e154}',
        Phosphor::ChartLineDown => '\u{e8b6}',
        Phosphor::ChartLineUp => '\u{e156}',
        Phosphor::ChartPie => '\u{e158}',
        Phosphor::ChartPieSlice => '\u{e15a}',
        Phosphor::ChartPolar => '\u{eaa8}',
        Phosphor::ChartScatter => '\u{eaac}',
        Phosphor::Chat => '\u{e15c}',
        Phosphor::ChatCentered => '\u{e160}',
        Phosphor::ChatCenteredDots => '\u{e164}',
        Phosphor::ChatCenteredSlash => '\u{e162}',
        Phosphor::ChatCenteredText => '\u{e166}',
        Phosphor::ChatCircle => '\u{e168}',
        Phosphor::ChatCircleDots => '\u{e16c}',
        Phosphor::ChatCircleSlash => '\u{e16a}',
        Phosphor::ChatCircleText => '\u{e16e}',
        Phosphor::ChatDots => '\u{e170}',
        Phosphor::ChatSlash => '\u{e15e}',
        Phosphor::ChatTeardrop => '\u{e172}',
        Phosphor::ChatTeardropDots => '\u{e176}',
        Phosphor::ChatTeardropSlash => '\u{e174}',
        Phosphor::ChatTeardropText => '\u{e178}',
        Phosphor::ChatText => '\u{e17a}',
        Phosphor::Chats => '\u{e17c}',
        Phosphor::ChatsCircle => '\u{e17e}',
        Phosphor::ChatsTeardrop => '\u{e180}',
        Phosphor::Check => '\u{e182}',
        Phosphor::CheckCircle => '\u{e184}',
        Phosphor::CheckFat => '\u{eba6}',
        Phosphor::CheckSquare => '\u{e186}',
        Phosphor::CheckSquareOffset => '\u{e188}',
        Phosphor::Checkerboard => '\u{e8c4}',
        Phosphor::Checks => '\u{e53a}',
        Phosphor::Cheers => '\u{ea4a}',
        Phosphor::Cheese => '\u{e9fe}',
        Phosphor::ChefHat => '\u{ed8e}',
        Phosphor::Cherries => '\u{e830}',
        Phosphor::Church => '\u{ecea}',
        Phosphor::Cigarette => '\u{ed90}',
        Phosphor::CigaretteSlash => '\u{ed92}',
        Phosphor::Circle => '\u{e18a}',
        Phosphor::CircleDashed => '\u{e602}',
        Phosphor::CircleHalf => '\u{e18c}',
        Phosphor::CircleHalfTilt => '\u{e18e}',
        Phosphor::CircleNotch => '\u{eb44}',
        Phosphor::CirclesFour => '\u{e190}',
        Phosphor::CirclesThree => '\u{e192}',
        Phosphor::CirclesThreePlus => '\u{e194}',
        Phosphor::Circuitry => '\u{e9c2}',
        Phosphor::City => '\u{ea6a}',
        Phosphor::Clipboard => '\u{e196}',
        Phosphor::ClipboardText => '\u{e198}',
        Phosphor::Clock => '\u{e19a}',
        Phosphor::ClockAfternoon => '\u{e19c}',
        Phosphor::ClockClockwise => '\u{e19e}',
        Phosphor::ClockCountdown => '\u{ed2c}',
        Phosphor::ClockCounterClockwise => '\u{e1a0}',
        Phosphor::ClockUser => '\u{edec}',
        Phosphor::ClosedCaptioning => '\u{e1a4}',
        Phosphor::Cloud => '\u{e1aa}',
        Phosphor::CloudArrowDown => '\u{e1ac}',
        Phosphor::CloudArrowUp => '\u{e1ae}',
        Phosphor::CloudCheck => '\u{e1b0}',
        Phosphor::CloudFog => '\u{e53c}',
        Phosphor::CloudLightning => '\u{e1b2}',
        Phosphor::CloudMoon => '\u{e53e}',
        Phosphor::CloudRain => '\u{e1b4}',
        Phosphor::CloudSlash => '\u{e1b6}',
        Phosphor::CloudSnow => '\u{e1b8}',
        Phosphor::CloudSun => '\u{e540}',
        Phosphor::CloudWarning => '\u{ea98}',
        Phosphor::CloudX => '\u{ea96}',
        Phosphor::Clover => '\u{edc8}',
        Phosphor::Club => '\u{e1ba}',
        Phosphor::CoatHanger => '\u{e7fe}',
        Phosphor::CodaLogo => '\u{e7ce}',
        Phosphor::Code => '\u{e1bc}',
        Phosphor::CodeBlock => '\u{eafe}',
        Phosphor::CodeSimple => '\u{e1be}',
        Phosphor::CodepenLogo => '\u{e978}',
        Phosphor::CodesandboxLogo => '\u{ea06}',
        Phosphor::Coffee => '\u{e1c2}',
        Phosphor::CoffeeBean => '\u{e1c0}',
        Phosphor::Coin => '\u{e60e}',
        Phosphor::CoinVertical => '\u{eb48}',
        Phosphor::Coins => '\u{e78e}',
        Phosphor::Columns => '\u{e546}',
        Phosphor::ColumnsPlusLeft => '\u{e544}',
        Phosphor::ColumnsPlusRight => '\u{e542}',
        Phosphor::Command => '\u{e1c4}',
        Phosphor::Compass => '\u{e1c8}',
        Phosphor::CompassRose => '\u{e1c6}',
        Phosphor::CompassTool => '\u{ea0e}',
        Phosphor::ComputerTower => '\u{e548}',
        Phosphor::Confetti => '\u{e81a}',
        Phosphor::ContactlessPayment => '\u{ed42}',
        Phosphor::Control => '\u{eca6}',
        Phosphor::Cookie => '\u{e6ca}',
        Phosphor::CookingPot => '\u{e764}',
        Phosphor::Copy => '\u{e1ca}',
        Phosphor::CopySimple => '\u{e1cc}',
        Phosphor::Copyleft => '\u{e86a}',
        Phosphor::Copyright => '\u{e54a}',
        Phosphor::CornersIn => '\u{e1ce}',
        Phosphor::CornersOut => '\u{e1d0}',
        Phosphor::Couch => '\u{e7f6}',
        Phosphor::CourtBasketball => '\u{ee36}',
        Phosphor::Cow => '\u{eabe}',
        Phosphor::CowboyHat => '\u{ed12}',
        Phosphor::Cpu => '\u{e610}',
        Phosphor::Crane => '\u{ed48}',
        Phosphor::CraneTower => '\u{ed49}',
        Phosphor::CreditCard => '\u{e1d2}',
        Phosphor::Cricket => '\u{ee12}',
        Phosphor::Crop => '\u{e1d4}',
        Phosphor::Cross => '\u{e8a0}',
        Phosphor::Crosshair => '\u{e1d6}',
        Phosphor::CrosshairSimple => '\u{e1d8}',
        Phosphor::Crown => '\u{e614}',
        Phosphor::CrownCross => '\u{ee5e}',
        Phosphor::CrownSimple => '\u{e616}',
        Phosphor::Cube => '\u{e1da}',
        Phosphor::CubeFocus => '\u{ed0a}',
        Phosphor::CubeTransparent => '\u{ec7c}',
        Phosphor::CurrencyBtc => '\u{e618}',
        Phosphor::CurrencyCircleDollar => '\u{e54c}',
        Phosphor::CurrencyCny => '\u{e54e}',
        Phosphor::CurrencyDollar => '\u{e550}',
        Phosphor::CurrencyDollarSimple => '\u{e552}',
        Phosphor::CurrencyEth => '\u{eada}',
        Phosphor::CurrencyEur => '\u{e554}',
        Phosphor::CurrencyGbp => '\u{e556}',
        Phosphor::CurrencyInr => '\u{e558}',
        Phosphor::CurrencyJpy => '\u{e55a}',
        Phosphor::CurrencyKrw => '\u{e55c}',
        Phosphor::CurrencyKzt => '\u{ec4c}',
        Phosphor::CurrencyNgn => '\u{eb52}',
        Phosphor::CurrencyRub => '\u{e55e}',
        Phosphor::Cursor => '\u{e1dc}',
        Phosphor::CursorClick => '\u{e7c8}',
        Phosphor::CursorText => '\u{e7d8}',
        Phosphor::Cylinder => '\u{e8fc}',
        Phosphor::Database => '\u{e1de}',
        Phosphor::Desk => '\u{ed16}',
        Phosphor::Desktop => '\u{e560}',
        Phosphor::DesktopTower => '\u{e562}',
        Phosphor::Detective => '\u{e83e}',
        Phosphor::DevToLogo => '\u{ed0e}',
        Phosphor::DeviceMobile => '\u{e1e0}',
        Phosphor::DeviceMobileCamera => '\u{e1e2}',
        Phosphor::DeviceMobileSlash => '\u{ee46}',
        Phosphor::DeviceMobileSpeaker => '\u{e1e4}',
        Phosphor::DeviceRotate => '\u{edf2}',
        Phosphor::DeviceTablet => '\u{e1e6}',
        Phosphor::DeviceTabletCamera => '\u{e1e8}',
        Phosphor::DeviceTabletSpeaker => '\u{e1ea}',
        Phosphor::Devices => '\u{eba4}',
        Phosphor::Diamond => '\u{e1ec}',
        Phosphor::DiamondsFour => '\u{e8f4}',
        Phosphor::DiceFive => '\u{e1ee}',
        Phosphor::DiceFour => '\u{e1f0}',
        Phosphor::DiceOne => '\u{e1f2}',
        Phosphor::DiceSix => '\u{e1f4}',
        Phosphor::DiceThree => '\u{e1f6}',
        Phosphor::DiceTwo => '\u{e1f8}',
        Phosphor::Disc => '\u{e564}',
        Phosphor::DiscoBall => '\u{ed98}',
        Phosphor::DiscordLogo => '\u{e61a}',
        Phosphor::Divide => '\u{e1fa}',
        Phosphor::Dna => '\u{e924}',
        Phosphor::Dog => '\u{e74a}',
        Phosphor::Door => '\u{e61c}',
        Phosphor::DoorOpen => '\u{e7e6}',
        Phosphor::Dot => '\u{ecde}',
        Phosphor::DotOutline => '\u{ece0}',
        Phosphor::DotsNine => '\u{e1fc}',
        Phosphor::DotsSix => '\u{e794}',
        Phosphor::DotsSixVertical => '\u{eae2}',
        Phosphor::DotsThree => '\u{e1fe}',
        Phosphor::DotsThreeCircle => '\u{e200}',
        Phosphor::DotsThreeCircleVertical => '\u{e202}',
        Phosphor::DotsThreeOutline => '\u{e204}',
        Phosphor::DotsThreeOutlineVertical => '\u{e206}',
        Phosphor::DotsThreeVertical => '\u{e208}',
        Phosphor::Download => '\u{e20a}',
        Phosphor::DownloadSimple => '\u{e20c}',
        Phosphor::Dress => '\u{ea7e}',
        Phosphor::Dresser => '\u{e94e}',
        Phosphor::DribbbleLogo => '\u{e20e}',
        Phosphor::Drone => '\u{ed74}',
        Phosphor::Drop => '\u{e210}',
        Phosphor::DropHalf => '\u{e566}',
        Phosphor::DropHalfBottom => '\u{eb40}',
        Phosphor::DropSimple => '\u{ee32}',
        Phosphor::DropSlash => '\u{e954}',
        Phosphor::DropboxLogo => '\u{e7d0}',
        Phosphor::Ear => '\u{e70c}',
        Phosphor::EarSlash => '\u{e70e}',
        Phosphor::Egg => '\u{e812}',
        Phosphor::EggCrack => '\u{eb64}',
        Phosphor::Eject => '\u{e212}',
        Phosphor::EjectSimple => '\u{e6ae}',
        Phosphor::Elevator => '\u{ecc0}',
        Phosphor::Empty => '\u{edbc}',
        Phosphor::Engine => '\u{ea80}',
        Phosphor::Envelope => '\u{e214}',
        Phosphor::EnvelopeOpen => '\u{e216}',
        Phosphor::EnvelopeSimple => '\u{e218}',
        Phosphor::EnvelopeSimpleOpen => '\u{e21a}',
        Phosphor::Equalizer => '\u{ebbc}',
        Phosphor::Equals => '\u{e21c}',
        Phosphor::Eraser => '\u{e21e}',
        Phosphor::EscalatorDown => '\u{ecba}',
        Phosphor::EscalatorUp => '\u{ecbc}',
        Phosphor::Exam => '\u{e742}',
        Phosphor::ExclamationMark => '\u{ee44}',
        Phosphor::Exclude => '\u{e882}',
        Phosphor::ExcludeSquare => '\u{e880}',
        Phosphor::Export => '\u{eaf0}',
        Phosphor::Eye => '\u{e220}',
        Phosphor::EyeClosed => '\u{e222}',
        Phosphor::EyeSlash => '\u{e224}',
        Phosphor::Eyedropper => '\u{e568}',
        Phosphor::EyedropperSample => '\u{eac4}',
        Phosphor::Eyeglasses => '\u{e7ba}',
        Phosphor::Eyes => '\u{ee5c}',
        Phosphor::FaceMask => '\u{e56a}',
        Phosphor::FacebookLogo => '\u{e226}',
        Phosphor::Factory => '\u{e760}',
        Phosphor::Faders => '\u{e228}',
        Phosphor::FadersHorizontal => '\u{e22a}',
        Phosphor::FalloutShelter => '\u{e9de}',
        Phosphor::Fan => '\u{e9f2}',
        Phosphor::Farm => '\u{ec70}',
        Phosphor::FastForward => '\u{e6a6}',
        Phosphor::FastForwardCircle => '\u{e22c}',
        Phosphor::Feather => '\u{e9c0}',
        Phosphor::FediverseLogo => '\u{ed66}',
        Phosphor::FigmaLogo => '\u{e22e}',
        Phosphor::File => '\u{e230}',
        Phosphor::FileArchive => '\u{eb2a}',
        Phosphor::FileArrowDown => '\u{e232}',
        Phosphor::FileArrowUp => '\u{e61e}',
        Phosphor::FileAudio => '\u{ea20}',
        Phosphor::FileC => '\u{eb32}',
        Phosphor::FileCSharp => '\u{eb30}',
        Phosphor::FileCloud => '\u{e95e}',
        Phosphor::FileCode => '\u{e914}',
        Phosphor::FileCpp => '\u{eb2e}',
        Phosphor::FileCss => '\u{eb34}',
        Phosphor::FileCsv => '\u{eb1c}',
        Phosphor::FileDashed => '\u{e704}',
        Phosphor::FileDotted => '\u{e704}',
        Phosphor::FileDoc => '\u{eb1e}',
        Phosphor::FileHtml => '\u{eb38}',
        Phosphor::FileImage => '\u{ea24}',
        Phosphor::FileIni => '\u{eb33}',
        Phosphor::FileJpg => '\u{eb1a}',
        Phosphor::FileJs => '\u{eb24}',
        Phosphor::FileJsx => '\u{eb3a}',
        Phosphor::FileLock => '\u{e95c}',
        Phosphor::FileMagnifyingGlass => '\u{e238}',
        Phosphor::FileSearch => '\u{e238}',
        Phosphor::FileMd => '\u{ed50}',
        Phosphor::FileMinus => '\u{e234}',
        Phosphor::FilePdf => '\u{e702}',
        Phosphor::FilePlus => '\u{e236}',
        Phosphor::FilePng => '\u{eb18}',
        Phosphor::FilePpt => '\u{eb20}',
        Phosphor::FilePy => '\u{eb2c}',
        Phosphor::FileRs => '\u{eb28}',
        Phosphor::FileSql => '\u{ed4e}',
        Phosphor::FileSvg => '\u{ed08}',
        Phosphor::FileText => '\u{e23a}',
        Phosphor::FileTs => '\u{eb26}',
        Phosphor::FileTsx => '\u{eb3c}',
        Phosphor::FileTxt => '\u{eb35}',
        Phosphor::FileVideo => '\u{ea22}',
        Phosphor::FileVue => '\u{eb3e}',
        Phosphor::FileX => '\u{e23c}',
        Phosphor::FileXls => '\u{eb22}',
        Phosphor::FileZip => '\u{e958}',
        Phosphor::Files => '\u{e710}',
        Phosphor::FilmReel => '\u{e8c0}',
        Phosphor::FilmScript => '\u{eb50}',
        Phosphor::FilmSlate => '\u{e8c2}',
        Phosphor::FilmStrip => '\u{e792}',
        Phosphor::Fingerprint => '\u{e23e}',
        Phosphor::FingerprintSimple => '\u{e240}',
        Phosphor::FinnTheHuman => '\u{e56c}',
        Phosphor::Fire => '\u{e242}',
        Phosphor::FireExtinguisher => '\u{e9e8}',
        Phosphor::FireSimple => '\u{e620}',
        Phosphor::FireTruck => '\u{e574}',
        Phosphor::FirstAid => '\u{e56e}',
        Phosphor::FirstAidKit => '\u{e570}',
        Phosphor::Fish => '\u{e728}',
        Phosphor::FishSimple => '\u{e72a}',
        Phosphor::Flag => '\u{e244}',
        Phosphor::FlagBanner => '\u{e622}',
        Phosphor::FlagBannerFold => '\u{ecf2}',
        Phosphor::FlagCheckered => '\u{ea38}',
        Phosphor::FlagPennant => '\u{ecf0}',
        Phosphor::Flame => '\u{e624}',
        Phosphor::Flashlight => '\u{e246}',
        Phosphor::Flask => '\u{e79e}',
        Phosphor::FlipHorizontal => '\u{ed6a}',
        Phosphor::FlipVertical => '\u{ed6c}',
        Phosphor::FloppyDisk => '\u{e248}',
        Phosphor::FloppyDiskBack => '\u{eaf4}',
        Phosphor::FlowArrow => '\u{e6ec}',
        Phosphor::Flower => '\u{e75e}',
        Phosphor::FlowerLotus => '\u{e6cc}',
        Phosphor::FlowerTulip => '\u{eacc}',
        Phosphor::FlyingSaucer => '\u{eb4a}',
        Phosphor::Folder => '\u{e24a}',
        Phosphor::FolderNotch => '\u{e24a}',
        Phosphor::FolderDashed => '\u{e8f8}',
        Phosphor::FolderDotted => '\u{e8f8}',
        Phosphor::FolderLock => '\u{ea3c}',
        Phosphor::FolderMinus => '\u{e254}',
        Phosphor::FolderNotchMinus => '\u{e254}',
        Phosphor::FolderOpen => '\u{e256}',
        Phosphor::FolderNotchOpen => '\u{e256}',
        Phosphor::FolderPlus => '\u{e258}',
        Phosphor::FolderNotchPlus => '\u{e258}',
        Phosphor::FolderSimple => '\u{e25a}',
        Phosphor::FolderSimpleDashed => '\u{ec2a}',
        Phosphor::FolderSimpleDotted => '\u{ec2a}',
        Phosphor::FolderSimpleLock => '\u{eb5e}',
        Phosphor::FolderSimpleMinus => '\u{e25c}',
        Phosphor::FolderSimplePlus => '\u{e25e}',
        Phosphor::FolderSimpleStar => '\u{ec2e}',
        Phosphor::FolderSimpleUser => '\u{eb60}',
        Phosphor::FolderStar => '\u{ea86}',
        Phosphor::FolderUser => '\u{eb46}',
        Phosphor::Folders => '\u{e260}',
        Phosphor::Football => '\u{e718}',
        Phosphor::FootballHelmet => '\u{ee4c}',
        Phosphor::Footprints => '\u{ea88}',
        Phosphor::ForkKnife => '\u{e262}',
        Phosphor::FourK => '\u{ea5c}',
        Phosphor::FrameCorners => '\u{e626}',
        Phosphor::FramerLogo => '\u{e264}',
        Phosphor::Function => '\u{ebe4}',
        Phosphor::Funnel => '\u{e266}',
        Phosphor::FunnelSimple => '\u{e268}',
        Phosphor::FunnelSimpleX => '\u{e26a}',
        Phosphor::FunnelX => '\u{e26c}',
        Phosphor::GameController => '\u{e26e}',
        Phosphor::Garage => '\u{ecd6}',
        Phosphor::GasCan => '\u{e8ce}',
        Phosphor::GasPump => '\u{e768}',
        Phosphor::Gauge => '\u{e628}',
        Phosphor::Gavel => '\u{ea32}',
        Phosphor::Gear => '\u{e270}',
        Phosphor::GearFine => '\u{e87c}',
        Phosphor::GearSix => '\u{e272}',
        Phosphor::GenderFemale => '\u{e6e0}',
        Phosphor::GenderIntersex => '\u{e6e6}',
        Phosphor::GenderMale => '\u{e6e2}',
        Phosphor::GenderNeuter => '\u{e6ea}',
        Phosphor::GenderNonbinary => '\u{e6e4}',
        Phosphor::GenderTransgender => '\u{e6e8}',
        Phosphor::Ghost => '\u{e62a}',
        Phosphor::Gif => '\u{e274}',
        Phosphor::Gift => '\u{e276}',
        Phosphor::GitBranch => '\u{e278}',
        Phosphor::GitCommit => '\u{e27a}',
        Phosphor::GitDiff => '\u{e27c}',
        Phosphor::GitFork => '\u{e27e}',
        Phosphor::GitMerge => '\u{e280}',
        Phosphor::GitPullRequest => '\u{e282}',
        Phosphor::GithubLogo => '\u{e576}',
        Phosphor::GitlabLogo => '\u{e694}',
        Phosphor::GitlabLogoSimple => '\u{e696}',
        Phosphor::Globe => '\u{e288}',
        Phosphor::GlobeHemisphereEast => '\u{e28a}',
        Phosphor::GlobeHemisphereWest => '\u{e28c}',
        Phosphor::GlobeSimple => '\u{e28e}',
        Phosphor::GlobeSimpleX => '\u{e284}',
        Phosphor::GlobeStand => '\u{e290}',
        Phosphor::GlobeX => '\u{e286}',
        Phosphor::Goggles => '\u{ecb4}',
        Phosphor::Golf => '\u{ea3e}',
        Phosphor::GoodreadsLogo => '\u{ed10}',
        Phosphor::GoogleCardboardLogo => '\u{e7b6}',
        Phosphor::GoogleChromeLogo => '\u{e976}',
        Phosphor::GoogleDriveLogo => '\u{e8f6}',
        Phosphor::GoogleLogo => '\u{e292}',
        Phosphor::GooglePhotosLogo => '\u{eb92}',
        Phosphor::GooglePlayLogo => '\u{e294}',
        Phosphor::GooglePodcastsLogo => '\u{eb94}',
        Phosphor::Gps => '\u{edd8}',
        Phosphor::GpsFix => '\u{edd6}',
        Phosphor::GpsSlash => '\u{edd4}',
        Phosphor::Gradient => '\u{eb42}',
        Phosphor::GraduationCap => '\u{e62c}',
        Phosphor::Grains => '\u{ec68}',
        Phosphor::GrainsSlash => '\u{ec6a}',
        Phosphor::Graph => '\u{eb58}',
        Phosphor::GraphicsCard => '\u{e612}',
        Phosphor::GreaterThan => '\u{edc4}',
        Phosphor::GreaterThanOrEqual => '\u{eda2}',
        Phosphor::GridFour => '\u{e296}',
        Phosphor::GridNine => '\u{ec8c}',
        Phosphor::Guitar => '\u{ea8a}',
        Phosphor::HairDryer => '\u{ea66}',
        Phosphor::Hamburger => '\u{e790}',
        Phosphor::Hammer => '\u{e80e}',
        Phosphor::Hand => '\u{e298}',
        Phosphor::HandArrowDown => '\u{ea4e}',
        Phosphor::HandArrowUp => '\u{ee5a}',
        Phosphor::HandCoins => '\u{ea8c}',
        Phosphor::HandDeposit => '\u{ee82}',
        Phosphor::HandEye => '\u{ea4c}',
        Phosphor::HandFist => '\u{e57a}',
        Phosphor::HandGrabbing => '\u{e57c}',
        Phosphor::HandHeart => '\u{e810}',
        Phosphor::HandPalm => '\u{e57e}',
        Phosphor::HandPeace => '\u{e7cc}',
        Phosphor::HandPointing => '\u{e29a}',
        Phosphor::HandSoap => '\u{e630}',
        Phosphor::HandSwipeLeft => '\u{ec94}',
        Phosphor::HandSwipeRight => '\u{ec92}',
        Phosphor::HandTap => '\u{ec90}',
        Phosphor::HandWaving => '\u{e580}',
        Phosphor::HandWithdraw => '\u{ee80}',
        Phosphor::Handbag => '\u{e29c}',
        Phosphor::HandbagSimple => '\u{e62e}',
        Phosphor::HandsClapping => '\u{e6a0}',
        Phosphor::HandsPraying => '\u{ecc8}',
        Phosphor::Handshake => '\u{e582}',
        Phosphor::HardDrive => '\u{e29e}',
        Phosphor::HardDrives => '\u{e2a0}',
        Phosphor::HardHat => '\u{ed46}',
        Phosphor::Hash => '\u{e2a2}',
        Phosphor::HashStraight => '\u{e2a4}',
        Phosphor::HeadCircuit => '\u{e7d4}',
        Phosphor::Headlights => '\u{e6fe}',
        Phosphor::Headphones => '\u{e2a6}',
        Phosphor::Headset => '\u{e584}',
        Phosphor::Heart => '\u{e2a8}',
        Phosphor::HeartBreak => '\u{ebe8}',
        Phosphor::HeartHalf => '\u{ec48}',
        Phosphor::HeartStraight => '\u{e2aa}',
        Phosphor::HeartStraightBreak => '\u{eb98}',
        Phosphor::Heartbeat => '\u{e2ac}',
        Phosphor::Hexagon => '\u{e2ae}',
        Phosphor::HighDefinition => '\u{ea8e}',
        Phosphor::HighHeel => '\u{e8e8}',
        Phosphor::Highlighter => '\u{ec76}',
        Phosphor::HighlighterCircle => '\u{e632}',
        Phosphor::Hockey => '\u{ec86}',
        Phosphor::Hoodie => '\u{ecd0}',
        Phosphor::Horse => '\u{e2b0}',
        Phosphor::Hospital => '\u{e844}',
        Phosphor::Hourglass => '\u{e2b2}',
        Phosphor::HourglassHigh => '\u{e2b4}',
        Phosphor::HourglassLow => '\u{e2b6}',
        Phosphor::HourglassMedium => '\u{e2b8}',
        Phosphor::HourglassSimple => '\u{e2ba}',
        Phosphor::HourglassSimpleHigh => '\u{e2bc}',
        Phosphor::HourglassSimpleLow => '\u{e2be}',
        Phosphor::HourglassSimpleMedium => '\u{e2c0}',
        Phosphor::House => '\u{e2c2}',
        Phosphor::HouseLine => '\u{e2c4}',
        Phosphor::HouseSimple => '\u{e2c6}',
        Phosphor::Hurricane => '\u{e88e}',
        Phosphor::IceCream => '\u{e804}',
        Phosphor::IdentificationBadge => '\u{e6f6}',
        Phosphor::IdentificationCard => '\u{e2c8}',
        Phosphor::Image => '\u{e2ca}',
        Phosphor::ImageBroken => '\u{e7a8}',
        Phosphor::ImageSquare => '\u{e2cc}',
        Phosphor::Images => '\u{e836}',
        Phosphor::ImagesSquare => '\u{e834}',
        Phosphor::Infinity => '\u{e634}',
        Phosphor::Lemniscate => '\u{e634}',
        Phosphor::Info => '\u{e2ce}',
        Phosphor::InstagramLogo => '\u{e2d0}',
        Phosphor::Intersect => '\u{e2d2}',
        Phosphor::IntersectSquare => '\u{e87a}',
        Phosphor::IntersectThree => '\u{ecc4}',
        Phosphor::Intersection => '\u{edba}',
        Phosphor::Invoice => '\u{ee42}',
        Phosphor::Island => '\u{ee06}',
        Phosphor::Jar => '\u{e7e0}',
        Phosphor::JarLabel => '\u{e7e1}',
        Phosphor::Jeep => '\u{e2d4}',
        Phosphor::Joystick => '\u{ea5e}',
        Phosphor::Kanban => '\u{eb54}',
        Phosphor::Key => '\u{e2d6}',
        Phosphor::KeyReturn => '\u{e782}',
        Phosphor::Keyboard => '\u{e2d8}',
        Phosphor::Keyhole => '\u{ea78}',
        Phosphor::Knife => '\u{e636}',
        Phosphor::Ladder => '\u{e9e4}',
        Phosphor::LadderSimple => '\u{ec26}',
        Phosphor::Lamp => '\u{e638}',
        Phosphor::LampPendant => '\u{ee2e}',
        Phosphor::Laptop => '\u{e586}',
        Phosphor::Lasso => '\u{edc6}',
        Phosphor::LastfmLogo => '\u{e842}',
        Phosphor::Layout => '\u{e6d6}',
        Phosphor::Leaf => '\u{e2da}',
        Phosphor::Lectern => '\u{e95a}',
        Phosphor::Lego => '\u{e8c6}',
        Phosphor::LegoSmiley => '\u{e8c7}',
        Phosphor::LessThan => '\u{edac}',
        Phosphor::LessThanOrEqual => '\u{eda4}',
        Phosphor::LetterCircleH => '\u{ebf8}',
        Phosphor::LetterCircleP => '\u{ec08}',
        Phosphor::LetterCircleV => '\u{ec14}',
        Phosphor::Lifebuoy => '\u{e63a}',
        Phosphor::Lightbulb => '\u{e2dc}',
        Phosphor::LightbulbFilament => '\u{e63c}',
        Phosphor::Lighthouse => '\u{e9f6}',
        Phosphor::Lightning => '\u{e2de}',
        Phosphor::LightningA => '\u{ea84}',
        Phosphor::LightningSlash => '\u{e2e0}',
        Phosphor::LineSegment => '\u{e6d2}',
        Phosphor::LineSegments => '\u{e6d4}',
        Phosphor::LineVertical => '\u{ed70}',
        Phosphor::Link => '\u{e2e2}',
        Phosphor::LinkBreak => '\u{e2e4}',
        Phosphor::LinkSimple => '\u{e2e6}',
        Phosphor::LinkSimpleBreak => '\u{e2e8}',
        Phosphor::LinkSimpleHorizontal => '\u{e2ea}',
        Phosphor::LinkSimpleHorizontalBreak => '\u{e2ec}',
        Phosphor::LinkedinLogo => '\u{e2ee}',
        Phosphor::LinktreeLogo => '\u{edee}',
        Phosphor::LinuxLogo => '\u{eb02}',
        Phosphor::List => '\u{e2f0}',
        Phosphor::ListBullets => '\u{e2f2}',
        Phosphor::ListChecks => '\u{eadc}',
        Phosphor::ListDashes => '\u{e2f4}',
        Phosphor::ListHeart => '\u{ebde}',
        Phosphor::ListMagnifyingGlass => '\u{ebe0}',
        Phosphor::ListNumbers => '\u{e2f6}',
        Phosphor::ListPlus => '\u{e2f8}',
        Phosphor::ListStar => '\u{ebdc}',
        Phosphor::Lock => '\u{e2fa}',
        Phosphor::LockKey => '\u{e2fe}',
        Phosphor::LockKeyOpen => '\u{e300}',
        Phosphor::LockLaminated => '\u{e302}',
        Phosphor::LockLaminatedOpen => '\u{e304}',
        Phosphor::LockOpen => '\u{e306}',
        Phosphor::LockSimple => '\u{e308}',
        Phosphor::LockSimpleOpen => '\u{e30a}',
        Phosphor::Lockers => '\u{ecb8}',
        Phosphor::Log => '\u{ed82}',
        Phosphor::MagicWand => '\u{e6b6}',
        Phosphor::Magnet => '\u{e680}',
        Phosphor::MagnetStraight => '\u{e682}',
        Phosphor::MagnifyingGlass => '\u{e30c}',
        Phosphor::MagnifyingGlassMinus => '\u{e30e}',
        Phosphor::MagnifyingGlassPlus => '\u{e310}',
        Phosphor::Mailbox => '\u{ec1e}',
        Phosphor::MapPin => '\u{e316}',
        Phosphor::MapPinArea => '\u{ee3a}',
        Phosphor::MapPinLine => '\u{e318}',
        Phosphor::MapPinPlus => '\u{e314}',
        Phosphor::MapPinSimple => '\u{ee3e}',
        Phosphor::MapPinSimpleArea => '\u{ee3c}',
        Phosphor::MapPinSimpleLine => '\u{ee38}',
        Phosphor::MapTrifold => '\u{e31a}',
        Phosphor::MarkdownLogo => '\u{e508}',
        Phosphor::MarkerCircle => '\u{e640}',
        Phosphor::Martini => '\u{e31c}',
        Phosphor::MaskHappy => '\u{e9f4}',
        Phosphor::MaskSad => '\u{eb9e}',
        Phosphor::MastodonLogo => '\u{ed68}',
        Phosphor::MathOperations => '\u{e31e}',
        Phosphor::MatrixLogo => '\u{ed64}',
        Phosphor::Medal => '\u{e320}',
        Phosphor::MedalMilitary => '\u{ecfc}',
        Phosphor::MediumLogo => '\u{e322}',
        Phosphor::Megaphone => '\u{e324}',
        Phosphor::MegaphoneSimple => '\u{e642}',
        Phosphor::MemberOf => '\u{edc2}',
        Phosphor::Memory => '\u{e9c4}',
        Phosphor::MessengerLogo => '\u{e6d8}',
        Phosphor::MetaLogo => '\u{ed02}',
        Phosphor::Meteor => '\u{e9ba}',
        Phosphor::Metronome => '\u{ec8e}',
        Phosphor::Microphone => '\u{e326}',
        Phosphor::MicrophoneSlash => '\u{e328}',
        Phosphor::MicrophoneStage => '\u{e75c}',
        Phosphor::Microscope => '\u{ec7a}',
        Phosphor::MicrosoftExcelLogo => '\u{eb6c}',
        Phosphor::MicrosoftOutlookLogo => '\u{eb70}',
        Phosphor::MicrosoftPowerpointLogo => '\u{eace}',
        Phosphor::MicrosoftTeamsLogo => '\u{eb66}',
        Phosphor::MicrosoftWordLogo => '\u{eb6a}',
        Phosphor::Minus => '\u{e32a}',
        Phosphor::MinusCircle => '\u{e32c}',
        Phosphor::MinusSquare => '\u{ed4c}',
        Phosphor::Money => '\u{e588}',
        Phosphor::MoneyWavy => '\u{ee68}',
        Phosphor::Monitor => '\u{e32e}',
        Phosphor::MonitorArrowUp => '\u{e58a}',
        Phosphor::MonitorPlay => '\u{e58c}',
        Phosphor::Moon => '\u{e330}',
        Phosphor::MoonStars => '\u{e58e}',
        Phosphor::Moped => '\u{e824}',
        Phosphor::MopedFront => '\u{e822}',
        Phosphor::Mosque => '\u{ecee}',
        Phosphor::Motorcycle => '\u{e80a}',
        Phosphor::Mountains => '\u{e7ae}',
        Phosphor::Mouse => '\u{e33a}',
        Phosphor::MouseLeftClick => '\u{e334}',
        Phosphor::MouseMiddleClick => '\u{e338}',
        Phosphor::MouseRightClick => '\u{e336}',
        Phosphor::MouseScroll => '\u{e332}',
        Phosphor::MouseSimple => '\u{e644}',
        Phosphor::MusicNote => '\u{e33c}',
        Phosphor::MusicNoteSimple => '\u{e33e}',
        Phosphor::MusicNotes => '\u{e340}',
        Phosphor::MusicNotesMinus => '\u{ee0c}',
        Phosphor::MusicNotesPlus => '\u{eb7c}',
        Phosphor::MusicNotesSimple => '\u{e342}',
        Phosphor::NavigationArrow => '\u{eade}',
        Phosphor::Needle => '\u{e82e}',
        Phosphor::Network => '\u{edde}',
        Phosphor::NetworkSlash => '\u{eddc}',
        Phosphor::NetworkX => '\u{edda}',
        Phosphor::Newspaper => '\u{e344}',
        Phosphor::NewspaperClipping => '\u{e346}',
        Phosphor::NotEquals => '\u{eda6}',
        Phosphor::NotMemberOf => '\u{edae}',
        Phosphor::NotSubsetOf => '\u{edb0}',
        Phosphor::NotSupersetOf => '\u{edb2}',
        Phosphor::Notches => '\u{ed3a}',
        Phosphor::Note => '\u{e348}',
        Phosphor::NoteBlank => '\u{e34a}',
        Phosphor::NotePencil => '\u{e34c}',
        Phosphor::Notebook => '\u{e34e}',
        Phosphor::Notepad => '\u{e63e}',
        Phosphor::Notification => '\u{e6fa}',
        Phosphor::NotionLogo => '\u{e9a0}',
        Phosphor::NuclearPlant => '\u{ed7c}',
        Phosphor::NumberCircleEight => '\u{e352}',
        Phosphor::NumberCircleFive => '\u{e358}',
        Phosphor::NumberCircleFour => '\u{e35e}',
        Phosphor::NumberCircleNine => '\u{e364}',
        Phosphor::NumberCircleOne => '\u{e36a}',
        Phosphor::NumberCircleSeven => '\u{e370}',
        Phosphor::NumberCircleSix => '\u{e376}',
        Phosphor::NumberCircleThree => '\u{e37c}',
        Phosphor::NumberCircleTwo => '\u{e382}',
        Phosphor::NumberCircleZero => '\u{e388}',
        Phosphor::NumberEight => '\u{e350}',
        Phosphor::NumberFive => '\u{e356}',
        Phosphor::NumberFour => '\u{e35c}',
        Phosphor::NumberNine => '\u{e362}',
        Phosphor::NumberOne => '\u{e368}',
        Phosphor::NumberSeven => '\u{e36e}',
        Phosphor::NumberSix => '\u{e374}',
        Phosphor::NumberSquareEight => '\u{e354}',
        Phosphor::NumberSquareFive => '\u{e35a}',
        Phosphor::NumberSquareFour => '\u{e360}',
        Phosphor::NumberSquareNine => '\u{e366}',
        Phosphor::NumberSquareOne => '\u{e36c}',
        Phosphor::NumberSquareSeven => '\u{e372}',
        Phosphor::NumberSquareSix => '\u{e378}',
        Phosphor::NumberSquareThree => '\u{e37e}',
        Phosphor::NumberSquareTwo => '\u{e384}',
        Phosphor::NumberSquareZero => '\u{e38a}',
        Phosphor::NumberThree => '\u{e37a}',
        Phosphor::NumberTwo => '\u{e380}',
        Phosphor::NumberZero => '\u{e386}',
        Phosphor::Numpad => '\u{e3c8}',
        Phosphor::Nut => '\u{e38c}',
        Phosphor::NyTimesLogo => '\u{e646}',
        Phosphor::Octagon => '\u{e38e}',
        Phosphor::OfficeChair => '\u{ea46}',
        Phosphor::Onigiri => '\u{ee2c}',
        Phosphor::OpenAiLogo => '\u{e7d2}',
        Phosphor::Option => '\u{e8a8}',
        Phosphor::Orange => '\u{ee40}',
        Phosphor::OrangeSlice => '\u{ed36}',
        Phosphor::Oven => '\u{ed8c}',
        Phosphor::Package => '\u{e390}',
        Phosphor::PaintBrush => '\u{e6f0}',
        Phosphor::PaintBrushBroad => '\u{e590}',
        Phosphor::PaintBrushHousehold => '\u{e6f2}',
        Phosphor::PaintBucket => '\u{e392}',
        Phosphor::PaintRoller => '\u{e6f4}',
        Phosphor::Palette => '\u{e6c8}',
        Phosphor::Panorama => '\u{eaa2}',
        Phosphor::Pants => '\u{ec88}',
        Phosphor::PaperPlane => '\u{e394}',
        Phosphor::PaperPlaneRight => '\u{e396}',
        Phosphor::PaperPlaneTilt => '\u{e398}',
        Phosphor::Paperclip => '\u{e39a}',
        Phosphor::PaperclipHorizontal => '\u{e592}',
        Phosphor::Parachute => '\u{ea7c}',
        Phosphor::Paragraph => '\u{e960}',
        Phosphor::Parallelogram => '\u{ecc6}',
        Phosphor::Park => '\u{ecb2}',
        Phosphor::Password => '\u{e752}',
        Phosphor::Path => '\u{e39c}',
        Phosphor::PatreonLogo => '\u{e98a}',
        Phosphor::Pause => '\u{e39e}',
        Phosphor::PauseCircle => '\u{e3a0}',
        Phosphor::PawPrint => '\u{e648}',
        Phosphor::PaypalLogo => '\u{e98c}',
        Phosphor::Peace => '\u{e3a2}',
        Phosphor::Pen => '\u{e3aa}',
        Phosphor::PenNib => '\u{e3ac}',
        Phosphor::PenNibStraight => '\u{e64a}',
        Phosphor::Pencil => '\u{e3ae}',
        Phosphor::PencilCircle => '\u{e3b0}',
        Phosphor::PencilLine => '\u{e3b2}',
        Phosphor::PencilRuler => '\u{e906}',
        Phosphor::PencilSimple => '\u{e3b4}',
        Phosphor::PencilSimpleLine => '\u{ebc6}',
        Phosphor::PencilSimpleSlash => '\u{ecf6}',
        Phosphor::PencilSlash => '\u{ecf8}',
        Phosphor::Pentagon => '\u{ec7e}',
        Phosphor::Pentagram => '\u{ec5c}',
        Phosphor::Pepper => '\u{e94a}',
        Phosphor::Percent => '\u{e3b6}',
        Phosphor::Person => '\u{e3a8}',
        Phosphor::PersonArmsSpread => '\u{ecfe}',
        Phosphor::PersonSimple => '\u{e72e}',
        Phosphor::PersonSimpleBike => '\u{e734}',
        Phosphor::PersonSimpleCircle => '\u{ee58}',
        Phosphor::PersonSimpleHike => '\u{ed54}',
        Phosphor::PersonSimpleRun => '\u{e730}',
        Phosphor::PersonSimpleSki => '\u{e71c}',
        Phosphor::PersonSimpleSnowboard => '\u{e71e}',
        Phosphor::PersonSimpleSwim => '\u{e736}',
        Phosphor::PersonSimpleTaiChi => '\u{ed5c}',
        Phosphor::PersonSimpleThrow => '\u{e732}',
        Phosphor::PersonSimpleWalk => '\u{e73a}',
        Phosphor::Perspective => '\u{ebe6}',
        Phosphor::Phone => '\u{e3b8}',
        Phosphor::PhoneCall => '\u{e3ba}',
        Phosphor::PhoneDisconnect => '\u{e3bc}',
        Phosphor::PhoneIncoming => '\u{e3be}',
        Phosphor::PhoneList => '\u{e3cc}',
        Phosphor::PhoneOutgoing => '\u{e3c0}',
        Phosphor::PhonePause => '\u{e3ca}',
        Phosphor::PhonePlus => '\u{ec56}',
        Phosphor::PhoneSlash => '\u{e3c2}',
        Phosphor::PhoneTransfer => '\u{e3c6}',
        Phosphor::PhoneX => '\u{e3c4}',
        Phosphor::Logo => '\u{e3ce}',
        Phosphor::Pi => '\u{ec80}',
        Phosphor::PianoKeys => '\u{e9c8}',
        Phosphor::PicnicTable => '\u{ee26}',
        Phosphor::PictureInPicture => '\u{e64c}',
        Phosphor::PiggyBank => '\u{ea04}',
        Phosphor::Pill => '\u{e700}',
        Phosphor::PingPong => '\u{ea42}',
        Phosphor::PintGlass => '\u{edd0}',
        Phosphor::PinterestLogo => '\u{e64e}',
        Phosphor::Pinwheel => '\u{eb9c}',
        Phosphor::Pipe => '\u{ed86}',
        Phosphor::PipeWrench => '\u{ed88}',
        Phosphor::PixLogo => '\u{ecc2}',
        Phosphor::Pizza => '\u{e796}',
        Phosphor::Placeholder => '\u{e650}',
        Phosphor::Planet => '\u{e652}',
        Phosphor::Plant => '\u{ebae}',
        Phosphor::Play => '\u{e3d0}',
        Phosphor::PlayCircle => '\u{e3d2}',
        Phosphor::PlayPause => '\u{e8be}',
        Phosphor::Playlist => '\u{e6aa}',
        Phosphor::Plug => '\u{e946}',
        Phosphor::PlugCharging => '\u{eb5c}',
        Phosphor::Plugs => '\u{eb56}',
        Phosphor::PlugsConnected => '\u{eb5a}',
        Phosphor::Plus => '\u{e3d4}',
        Phosphor::PlusCircle => '\u{e3d6}',
        Phosphor::PlusMinus => '\u{e3d8}',
        Phosphor::PlusSquare => '\u{ed4a}',
        Phosphor::PokerChip => '\u{e594}',
        Phosphor::PoliceCar => '\u{ec4a}',
        Phosphor::Polygon => '\u{e6d0}',
        Phosphor::Popcorn => '\u{eb4e}',
        Phosphor::Popsicle => '\u{ebbe}',
        Phosphor::PottedPlant => '\u{ec22}',
        Phosphor::Power => '\u{e3da}',
        Phosphor::Prescription => '\u{e7a2}',
        Phosphor::Presentation => '\u{e654}',
        Phosphor::PresentationChart => '\u{e656}',
        Phosphor::Printer => '\u{e3dc}',
        Phosphor::Prohibit => '\u{e3de}',
        Phosphor::ProhibitInset => '\u{e3e0}',
        Phosphor::ProjectorScreen => '\u{e658}',
        Phosphor::ProjectorScreenChart => '\u{e65a}',
        Phosphor::Pulse => '\u{e000}',
        Phosphor::Activity => '\u{e000}',
        Phosphor::PushPin => '\u{e3e2}',
        Phosphor::PushPinSimple => '\u{e65c}',
        Phosphor::PushPinSimpleSlash => '\u{e65e}',
        Phosphor::PushPinSlash => '\u{e3e4}',
        Phosphor::PuzzlePiece => '\u{e596}',
        Phosphor::QrCode => '\u{e3e6}',
        Phosphor::Question => '\u{e3e8}',
        Phosphor::QuestionMark => '\u{e3e9}',
        Phosphor::Queue => '\u{e6ac}',
        Phosphor::Quotes => '\u{e660}',
        Phosphor::Rabbit => '\u{eac2}',
        Phosphor::Racquet => '\u{ee02}',
        Phosphor::Radical => '\u{e3ea}',
        Phosphor::Radio => '\u{e77e}',
        Phosphor::RadioButton => '\u{eb08}',
        Phosphor::Radioactive => '\u{e9dc}',
        Phosphor::Rainbow => '\u{e598}',
        Phosphor::RainbowCloud => '\u{e59a}',
        Phosphor::Ranking => '\u{ed62}',
        Phosphor::ReadCvLogo => '\u{ed0c}',
        Phosphor::Receipt => '\u{e3ec}',
        Phosphor::ReceiptX => '\u{ed40}',
        Phosphor::Record => '\u{e3ee}',
        Phosphor::Rectangle => '\u{e3f0}',
        Phosphor::RectangleDashed => '\u{e3f2}',
        Phosphor::Recycle => '\u{e75a}',
        Phosphor::RedditLogo => '\u{e59c}',
        Phosphor::Repeat => '\u{e3f6}',
        Phosphor::RepeatOnce => '\u{e3f8}',
        Phosphor::ReplitLogo => '\u{eb8a}',
        Phosphor::Resize => '\u{ed6e}',
        Phosphor::Rewind => '\u{e6a8}',
        Phosphor::RewindCircle => '\u{e3fa}',
        Phosphor::RoadHorizon => '\u{e838}',
        Phosphor::Robot => '\u{e762}',
        Phosphor::Rocket => '\u{e3fc}',
        Phosphor::RocketLaunch => '\u{e3fe}',
        Phosphor::Rows => '\u{e5a2}',
        Phosphor::RowsPlusBottom => '\u{e59e}',
        Phosphor::RowsPlusTop => '\u{e5a0}',
        Phosphor::Rss => '\u{e400}',
        Phosphor::RssSimple => '\u{e402}',
        Phosphor::Rug => '\u{ea1a}',
        Phosphor::Ruler => '\u{e6b8}',
        Phosphor::Sailboat => '\u{e78a}',
        Phosphor::Scales => '\u{e750}',
        Phosphor::Scan => '\u{ebb6}',
        Phosphor::ScanSmiley => '\u{ebb4}',
        Phosphor::Scissors => '\u{eae0}',
        Phosphor::Scooter => '\u{e820}',
        Phosphor::Screencast => '\u{e404}',
        Phosphor::Screwdriver => '\u{e86e}',
        Phosphor::Scribble => '\u{e806}',
        Phosphor::ScribbleLoop => '\u{e662}',
        Phosphor::Scroll => '\u{eb7a}',
        Phosphor::Seal => '\u{e604}',
        Phosphor::CircleWavy => '\u{e604}',
        Phosphor::SealCheck => '\u{e606}',
        Phosphor::CircleWavyCheck => '\u{e606}',
        Phosphor::SealPercent => '\u{e60a}',
        Phosphor::SealQuestion => '\u{e608}',
        Phosphor::CircleWavyQuestion => '\u{e608}',
        Phosphor::SealWarning => '\u{e60c}',
        Phosphor::CircleWavyWarning => '\u{e60c}',
        Phosphor::Seat => '\u{eb8e}',
        Phosphor::Seatbelt => '\u{edfe}',
        Phosphor::SecurityCamera => '\u{eca4}',
        Phosphor::Selection => '\u{e69a}',
        Phosphor::SelectionAll => '\u{e746}',
        Phosphor::SelectionBackground => '\u{eaf8}',
        Phosphor::SelectionForeground => '\u{eaf6}',
        Phosphor::SelectionInverse => '\u{e744}',
        Phosphor::SelectionPlus => '\u{e69c}',
        Phosphor::SelectionSlash => '\u{e69e}',
        Phosphor::Shapes => '\u{ec5e}',
        Phosphor::Share => '\u{e406}',
        Phosphor::ShareFat => '\u{ed52}',
        Phosphor::ShareNetwork => '\u{e408}',
        Phosphor::Shield => '\u{e40a}',
        Phosphor::ShieldCheck => '\u{e40c}',
        Phosphor::ShieldCheckered => '\u{e708}',
        Phosphor::ShieldChevron => '\u{e40e}',
        Phosphor::ShieldPlus => '\u{e706}',
        Phosphor::ShieldSlash => '\u{e410}',
        Phosphor::ShieldStar => '\u{ec34}',
        Phosphor::ShieldWarning => '\u{e412}',
        Phosphor::ShippingContainer => '\u{e78c}',
        Phosphor::ShirtFolded => '\u{ea92}',
        Phosphor::ShootingStar => '\u{ecfa}',
        Phosphor::ShoppingBag => '\u{e416}',
        Phosphor::ShoppingBagOpen => '\u{e418}',
        Phosphor::ShoppingCart => '\u{e41e}',
        Phosphor::ShoppingCartSimple => '\u{e420}',
        Phosphor::Shovel => '\u{e9e6}',
        Phosphor::Shower => '\u{e776}',
        Phosphor::Shrimp => '\u{eab4}',
        Phosphor::Shuffle => '\u{e422}',
        Phosphor::ShuffleAngular => '\u{e424}',
        Phosphor::ShuffleSimple => '\u{e426}',
        Phosphor::Sidebar => '\u{eab6}',
        Phosphor::SidebarSimple => '\u{ec24}',
        Phosphor::Sigma => '\u{eab8}',
        Phosphor::SignIn => '\u{e428}',
        Phosphor::SignOut => '\u{e42a}',
        Phosphor::Signature => '\u{ebac}',
        Phosphor::Signpost => '\u{e89c}',
        Phosphor::SimCard => '\u{e664}',
        Phosphor::Siren => '\u{e9b8}',
        Phosphor::SketchLogo => '\u{e42c}',
        Phosphor::SkipBack => '\u{e5a4}',
        Phosphor::SkipBackCircle => '\u{e42e}',
        Phosphor::SkipForward => '\u{e5a6}',
        Phosphor::SkipForwardCircle => '\u{e430}',
        Phosphor::Skull => '\u{e916}',
        Phosphor::SkypeLogo => '\u{e8dc}',
        Phosphor::SlackLogo => '\u{e5a8}',
        Phosphor::Sliders => '\u{e432}',
        Phosphor::SlidersHorizontal => '\u{e434}',
        Phosphor::Slideshow => '\u{ed32}',
        Phosphor::Smiley => '\u{e436}',
        Phosphor::SmileyAngry => '\u{ec62}',
        Phosphor::SmileyBlank => '\u{e438}',
        Phosphor::SmileyMeh => '\u{e43a}',
        Phosphor::SmileyMelting => '\u{ee56}',
        Phosphor::SmileyNervous => '\u{e43c}',
        Phosphor::SmileySad => '\u{e43e}',
        Phosphor::SmileySticker => '\u{e440}',
        Phosphor::SmileyWink => '\u{e666}',
        Phosphor::SmileyXEyes => '\u{e442}',
        Phosphor::SnapchatLogo => '\u{e668}',
        Phosphor::Sneaker => '\u{e80c}',
        Phosphor::SneakerMove => '\u{ed60}',
        Phosphor::Snowflake => '\u{e5aa}',
        Phosphor::SoccerBall => '\u{e716}',
        Phosphor::Sock => '\u{ecce}',
        Phosphor::SolarPanel => '\u{ed7a}',
        Phosphor::SolarRoof => '\u{ed7b}',
        Phosphor::SortAscending => '\u{e444}',
        Phosphor::SortDescending => '\u{e446}',
        Phosphor::SoundcloudLogo => '\u{e8de}',
        Phosphor::Spade => '\u{e448}',
        Phosphor::Sparkle => '\u{e6a2}',
        Phosphor::SpeakerHifi => '\u{ea08}',
        Phosphor::SpeakerHigh => '\u{e44a}',
        Phosphor::SpeakerLow => '\u{e44c}',
        Phosphor::SpeakerNone => '\u{e44e}',
        Phosphor::SpeakerSimpleHigh => '\u{e450}',
        Phosphor::SpeakerSimpleLow => '\u{e452}',
        Phosphor::SpeakerSimpleNone => '\u{e454}',
        Phosphor::SpeakerSimpleSlash => '\u{e456}',
        Phosphor::SpeakerSimpleX => '\u{e458}',
        Phosphor::SpeakerSlash => '\u{e45a}',
        Phosphor::SpeakerX => '\u{e45c}',
        Phosphor::Speedometer => '\u{ee74}',
        Phosphor::Sphere => '\u{ee66}',
        Phosphor::Spinner => '\u{e66a}',
        Phosphor::SpinnerBall => '\u{ee28}',
        Phosphor::SpinnerGap => '\u{e66c}',
        Phosphor::Spiral => '\u{e9fa}',
        Phosphor::SplitHorizontal => '\u{e872}',
        Phosphor::SplitVertical => '\u{e876}',
        Phosphor::SpotifyLogo => '\u{e66e}',
        Phosphor::SprayBottle => '\u{e7e4}',
        Phosphor::Square => '\u{e45e}',
        Phosphor::SquareHalf => '\u{e462}',
        Phosphor::SquareHalfBottom => '\u{eb16}',
        Phosphor::SquareLogo => '\u{e690}',
        Phosphor::SquareSplitHorizontal => '\u{e870}',
        Phosphor::SquareSplitVertical => '\u{e874}',
        Phosphor::SquaresFour => '\u{e464}',
        Phosphor::Stack => '\u{e466}',
        Phosphor::StackMinus => '\u{edf4}',
        Phosphor::StackOverflowLogo => '\u{eb78}',
        Phosphor::StackPlus => '\u{edf6}',
        Phosphor::StackSimple => '\u{e468}',
        Phosphor::Stairs => '\u{e8ec}',
        Phosphor::Stamp => '\u{ea48}',
        Phosphor::StandardDefinition => '\u{ea90}',
        Phosphor::Star => '\u{e46a}',
        Phosphor::StarAndCrescent => '\u{ecf4}',
        Phosphor::StarFour => '\u{e6a4}',
        Phosphor::StarHalf => '\u{e70a}',
        Phosphor::StarOfDavid => '\u{e89e}',
        Phosphor::SteamLogo => '\u{ead4}',
        Phosphor::SteeringWheel => '\u{e9ac}',
        Phosphor::Steps => '\u{ecbe}',
        Phosphor::Stethoscope => '\u{e7ea}',
        Phosphor::Sticker => '\u{e5ac}',
        Phosphor::Stool => '\u{ea44}',
        Phosphor::Stop => '\u{e46c}',
        Phosphor::StopCircle => '\u{e46e}',
        Phosphor::Storefront => '\u{e470}',
        Phosphor::Strategy => '\u{ea3a}',
        Phosphor::StripeLogo => '\u{e698}',
        Phosphor::Student => '\u{e73e}',
        Phosphor::SubsetOf => '\u{edc0}',
        Phosphor::SubsetProperOf => '\u{edb6}',
        Phosphor::Subtitles => '\u{e1a8}',
        Phosphor::SubtitlesSlash => '\u{e1a6}',
        Phosphor::Subtract => '\u{ebd6}',
        Phosphor::SubtractSquare => '\u{ebd4}',
        Phosphor::Subway => '\u{e498}',
        Phosphor::Suitcase => '\u{e5ae}',
        Phosphor::SuitcaseRolling => '\u{e9b0}',
        Phosphor::SuitcaseSimple => '\u{e5b0}',
        Phosphor::Sun => '\u{e472}',
        Phosphor::SunDim => '\u{e474}',
        Phosphor::SunHorizon => '\u{e5b6}',
        Phosphor::Sunglasses => '\u{e816}',
        Phosphor::SupersetOf => '\u{edb8}',
        Phosphor::SupersetProperOf => '\u{edb4}',
        Phosphor::Swap => '\u{e83c}',
        Phosphor::Swatches => '\u{e5b8}',
        Phosphor::SwimmingPool => '\u{ecb6}',
        Phosphor::Sword => '\u{e5ba}',
        Phosphor::Synagogue => '\u{ecec}',
        Phosphor::Syringe => '\u{e968}',
        Phosphor::TShirt => '\u{e670}',
        Phosphor::Table => '\u{e476}',
        Phosphor::Tabs => '\u{e778}',
        Phosphor::Tag => '\u{e478}',
        Phosphor::TagChevron => '\u{e672}',
        Phosphor::TagSimple => '\u{e47a}',
        Phosphor::Target => '\u{e47c}',
        Phosphor::Taxi => '\u{e902}',
        Phosphor::TeaBag => '\u{e8e6}',
        Phosphor::TelegramLogo => '\u{e5bc}',
        Phosphor::Television => '\u{e754}',
        Phosphor::TelevisionSimple => '\u{eae6}',
        Phosphor::TennisBall => '\u{e720}',
        Phosphor::Tent => '\u{e8ba}',
        Phosphor::Terminal => '\u{e47e}',
        Phosphor::TerminalWindow => '\u{eae8}',
        Phosphor::TestTube => '\u{e7a0}',
        Phosphor::TextAUnderline => '\u{ed34}',
        Phosphor::TextAa => '\u{e6ee}',
        Phosphor::TextAlignCenter => '\u{e480}',
        Phosphor::TextAlignJustify => '\u{e482}',
        Phosphor::TextAlignLeft => '\u{e484}',
        Phosphor::TextAlignRight => '\u{e486}',
        Phosphor::TextB => '\u{e5be}',
        Phosphor::TextBolder => '\u{e5be}',
        Phosphor::TextColumns => '\u{ec96}',
        Phosphor::TextH => '\u{e6ba}',
        Phosphor::TextHFive => '\u{e6c4}',
        Phosphor::TextHFour => '\u{e6c2}',
        Phosphor::TextHOne => '\u{e6bc}',
        Phosphor::TextHSix => '\u{e6c6}',
        Phosphor::TextHThree => '\u{e6c0}',
        Phosphor::TextHTwo => '\u{e6be}',
        Phosphor::TextIndent => '\u{ea1e}',
        Phosphor::TextItalic => '\u{e5c0}',
        Phosphor::TextOutdent => '\u{ea1c}',
        Phosphor::TextStrikethrough => '\u{e5c2}',
        Phosphor::TextSubscript => '\u{ec98}',
        Phosphor::TextSuperscript => '\u{ec9a}',
        Phosphor::TextT => '\u{e48a}',
        Phosphor::TextTSlash => '\u{e488}',
        Phosphor::TextUnderline => '\u{e5c4}',
        Phosphor::Textbox => '\u{eb0a}',
        Phosphor::Thermometer => '\u{e5c6}',
        Phosphor::ThermometerCold => '\u{e5c8}',
        Phosphor::ThermometerHot => '\u{e5ca}',
        Phosphor::ThermometerSimple => '\u{e5cc}',
        Phosphor::ThreadsLogo => '\u{ed9e}',
        Phosphor::ThreeD => '\u{ea5a}',
        Phosphor::ThumbsDown => '\u{e48c}',
        Phosphor::ThumbsUp => '\u{e48e}',
        Phosphor::Ticket => '\u{e490}',
        Phosphor::TidalLogo => '\u{ed1c}',
        Phosphor::TiktokLogo => '\u{eaf2}',
        Phosphor::Tilde => '\u{eda8}',
        Phosphor::Timer => '\u{e492}',
        Phosphor::TipJar => '\u{e7e2}',
        Phosphor::Tipi => '\u{ed30}',
        Phosphor::Tire => '\u{edd2}',
        Phosphor::ToggleLeft => '\u{e674}',
        Phosphor::ToggleRight => '\u{e676}',
        Phosphor::Toilet => '\u{e79a}',
        Phosphor::ToiletPaper => '\u{e79c}',
        Phosphor::Toolbox => '\u{eca0}',
        Phosphor::Tooth => '\u{e9cc}',
        Phosphor::Tornado => '\u{e88c}',
        Phosphor::Tote => '\u{e494}',
        Phosphor::ToteSimple => '\u{e678}',
        Phosphor::Towel => '\u{ede6}',
        Phosphor::Tractor => '\u{ec6e}',
        Phosphor::Trademark => '\u{e9f0}',
        Phosphor::TrademarkRegistered => '\u{e3f4}',
        Phosphor::TrafficCone => '\u{e9a8}',
        Phosphor::TrafficSign => '\u{e67a}',
        Phosphor::TrafficSignal => '\u{e9aa}',
        Phosphor::Train => '\u{e496}',
        Phosphor::TrainRegional => '\u{e49e}',
        Phosphor::TrainSimple => '\u{e4a0}',
        Phosphor::Tram => '\u{e9ec}',
        Phosphor::Translate => '\u{e4a2}',
        Phosphor::Trash => '\u{e4a6}',
        Phosphor::TrashSimple => '\u{e4a8}',
        Phosphor::Tray => '\u{e4aa}',
        Phosphor::TrayArrowDown => '\u{e010}',
        Phosphor::ArchiveTray => '\u{e010}',
        Phosphor::TrayArrowUp => '\u{ee52}',
        Phosphor::TreasureChest => '\u{ede2}',
        Phosphor::Tree => '\u{e6da}',
        Phosphor::TreeEvergreen => '\u{e6dc}',
        Phosphor::TreePalm => '\u{e91a}',
        Phosphor::TreeStructure => '\u{e67c}',
        Phosphor::TreeView => '\u{ee48}',
        Phosphor::TrendDown => '\u{e4ac}',
        Phosphor::TrendUp => '\u{e4ae}',
        Phosphor::Triangle => '\u{e4b0}',
        Phosphor::TriangleDashed => '\u{e4b2}',
        Phosphor::Trolley => '\u{e5b2}',
        Phosphor::TrolleySuitcase => '\u{e5b4}',
        Phosphor::Trophy => '\u{e67e}',
        Phosphor::Truck => '\u{e4b4}',
        Phosphor::TruckTrailer => '\u{e4b6}',
        Phosphor::TumblrLogo => '\u{e8d4}',
        Phosphor::TwitchLogo => '\u{e5ce}',
        Phosphor::TwitterLogo => '\u{e4ba}',
        Phosphor::Umbrella => '\u{e684}',
        Phosphor::UmbrellaSimple => '\u{e686}',
        Phosphor::Union => '\u{edbe}',
        Phosphor::Unite => '\u{e87e}',
        Phosphor::UniteSquare => '\u{e878}',
        Phosphor::Upload => '\u{e4be}',
        Phosphor::UploadSimple => '\u{e4c0}',
        Phosphor::Usb => '\u{e956}',
        Phosphor::User => '\u{e4c2}',
        Phosphor::UserCheck => '\u{eafa}',
        Phosphor::UserCircle => '\u{e4c4}',
        Phosphor::UserCircleCheck => '\u{ec38}',
        Phosphor::UserCircleDashed => '\u{ec36}',
        Phosphor::UserCircleGear => '\u{e4c6}',
        Phosphor::UserCircleMinus => '\u{e4c8}',
        Phosphor::UserCirclePlus => '\u{e4ca}',
        Phosphor::UserFocus => '\u{e6fc}',
        Phosphor::UserGear => '\u{e4cc}',
        Phosphor::UserList => '\u{e73c}',
        Phosphor::UserMinus => '\u{e4ce}',
        Phosphor::UserPlus => '\u{e4d0}',
        Phosphor::UserRectangle => '\u{e4d2}',
        Phosphor::UserSound => '\u{eca8}',
        Phosphor::UserSquare => '\u{e4d4}',
        Phosphor::UserSwitch => '\u{e756}',
        Phosphor::Users => '\u{e4d6}',
        Phosphor::UsersFour => '\u{e68c}',
        Phosphor::UsersThree => '\u{e68e}',
        Phosphor::Van => '\u{e826}',
        Phosphor::Vault => '\u{e76e}',
        Phosphor::VectorThree => '\u{ee62}',
        Phosphor::VectorTwo => '\u{ee64}',
        Phosphor::Vibrate => '\u{e4d8}',
        Phosphor::Video => '\u{e740}',
        Phosphor::VideoCamera => '\u{e4da}',
        Phosphor::VideoCameraSlash => '\u{e4dc}',
        Phosphor::VideoConference => '\u{edce}',
        Phosphor::Vignette => '\u{eba2}',
        Phosphor::VinylRecord => '\u{ecac}',
        Phosphor::VirtualReality => '\u{e7b8}',
        Phosphor::Virus => '\u{e7d6}',
        Phosphor::Visor => '\u{ee2a}',
        Phosphor::Voicemail => '\u{e4de}',
        Phosphor::Volleyball => '\u{e726}',
        Phosphor::Wall => '\u{e688}',
        Phosphor::Wallet => '\u{e68a}',
        Phosphor::Warehouse => '\u{ecd4}',
        Phosphor::Warning => '\u{e4e0}',
        Phosphor::WarningCircle => '\u{e4e2}',
        Phosphor::WarningDiamond => '\u{e7fc}',
        Phosphor::WarningOctagon => '\u{e4e4}',
        Phosphor::WashingMachine => '\u{ede8}',
        Phosphor::Watch => '\u{e4e6}',
        Phosphor::WaveSawtooth => '\u{ea9c}',
        Phosphor::WaveSine => '\u{ea9a}',
        Phosphor::WaveSquare => '\u{ea9e}',
        Phosphor::WaveTriangle => '\u{eaa0}',
        Phosphor::Waveform => '\u{e802}',
        Phosphor::WaveformSlash => '\u{e800}',
        Phosphor::Waves => '\u{e6de}',
        Phosphor::Webcam => '\u{e9b2}',
        Phosphor::WebcamSlash => '\u{ecdc}',
        Phosphor::WebhooksLogo => '\u{ecae}',
        Phosphor::WechatLogo => '\u{e8d2}',
        Phosphor::WhatsappLogo => '\u{e5d0}',
        Phosphor::Wheelchair => '\u{e4e8}',
        Phosphor::WheelchairMotion => '\u{e89a}',
        Phosphor::WifiHigh => '\u{e4ea}',
        Phosphor::WifiLow => '\u{e4ec}',
        Phosphor::WifiMedium => '\u{e4ee}',
        Phosphor::WifiNone => '\u{e4f0}',
        Phosphor::WifiSlash => '\u{e4f2}',
        Phosphor::WifiX => '\u{e4f4}',
        Phosphor::Wind => '\u{e5d2}',
        Phosphor::Windmill => '\u{e9f8}',
        Phosphor::WindowsLogo => '\u{e692}',
        Phosphor::Wine => '\u{e6b2}',
        Phosphor::Wrench => '\u{e5d4}',
        Phosphor::X => '\u{e4f6}',
        Phosphor::XCircle => '\u{e4f8}',
        Phosphor::XLogo => '\u{e4bc}',
        Phosphor::XSquare => '\u{e4fa}',
        Phosphor::Yarn => '\u{ed9a}',
        Phosphor::YinYang => '\u{e92a}',
        Phosphor::YoutubeLogo => '\u{e4fc}',
    }
}

/// Converts an [`Phosphor`] into a [`char`]
#[must_use]
pub fn icon_to_string(icon: Phosphor) -> String {
    icon_to_char(icon).to_string()
}

impl Display for Phosphor {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        write!(f, "{}", icon_to_char(*self))
    }
}

impl From<Phosphor> for char {
    fn from(icon: Phosphor) -> Self {
        icon_to_char(icon)
    }
}

impl From<Phosphor> for String {
    fn from(icon: Phosphor) -> Self {
        format!("{}", icon_to_char(icon))
    }
}
